- src/main/scala/io/snyk/plugin/ui/actions/SnykToggleGroupDisplayAction.scala
Replaced AllIcons.General.HideDownPart with AllIcons.General.HideToolWindow because HideDownPart icon are going to be removed in the upcoming IntelliJ Platform 2020.1 release.
> Fix: replace deprecated icon with new version.

- src/main/resources/META-INF/plugin.xml
- src/main/scala/io/snyk/plugin/ui/annotators/SnykMavenRedUnderlineAnnotator.scala
- src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
- src/test/resources/sample-response-for-annotator-test.json
- src/test/scala/io/snyk/plugin/SnykMavenRedUnderlineAnnotatorTest.scala
This will add a red underline for Maven vulnerabilities.
> Feat: add red underline annotator for maven vulnerabilities

- src/main/resources/META-INF/plugin.xml
Removed "Toggle display of Maven Groups" button.
> Fix: removed "Toggle display of Maven Groups" button.

- src/main/resources/META-INF/plugin.xml
This PR adds additional information in plugin overview about CLI installation for v2.
> docs: add information in overview that CLI must be installed for v2

- src/main/scala/io/snyk/plugin/client/CliClient.scala
- src/test/scala/io/snyk/plugin/SnykGradleMultiModuleTest.scala
Fix issue with Snyk CLI not found on Windows OS. Now the plugin checks the type of operating system and returns the corresponding command name. If it's Windows OS it will return "snyk.cmd". If it's Unix/Linux Os it will return "snyk".
> Fix: fix issue with Snyk CLI not found on Windows OS.

- src/main/resources/META-INF/plugin.xml
We add `until-build` attribute to set maximum build of IDE compatible with our plugin.
Build number ranges: https://jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html
> feat: add until-build attribute to plugin.xml

- gradle.properties
- src/main/scala/io/snyk/plugin/client/CliClient.scala
- src/test/scala/io/snyk/plugin/SnykCliClientTest.scala
Fixed CLI parameters in the case of the Gradle package manager. 
If --file parameter exists it will not use --all-sub-projects parameter, otherwise it will use --all-sub-projects.
> Fix: Gradle CLI parameters

- CHANGELOG.md
- build.gradle.kts
This PR adds latest changelog item in `plugin.xml` during `patchChangeLog` task.
Example screenshot:
> chore: patch plugin.xml with latest changelog item

- CHANGELOG.md
- build.gradle.kts
This PR removes patchChanglog gradle task during publishing phase.
> fix: remove patch changelog task dependency

- gradle.properties
- src/main/kotlin/io/snyk/plugin/services/SnykCliService.kt
- src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt
Had a bunch of issues with Snyk plugin for Android Studio since our setup requires the usage of several flags (--configuration-matches, --severity-threshold and --sub-project)
Discussed this with Trevor McCord over several emails since we're evaluating getting on board with Snyk. Discovered that SnykCLIService bundles them up in a single argument and apparently only the first arg is correctly parsed and the rest gets ignored or throws an error.
Android-studio log
`2020-11-12 10:27:02,635 [60825005]   INFO - plugin.services.SnykCliService - Cli parameters: [/Users/vmacias/Library/Application Support/Google/AndroidStudio4.1/plugins/snyk-intellij-plugin/snyk-macos, --json, --org=billpocket, --severity-threshold=low --sub-project=billpocket …
> feat: Naively split the additionalParameters value so the CommandLineRunner sends them correctly as separate arguments

- gradle.properties
IntelliJ 2020.3 is out: https://blog.jetbrains.com/idea/2020/12/intellij-idea-2020-3/
This PR bumps `pluginUntilBuild` property to 203.*, so users can install it on new versions.
> chore: allow to install the plugin on IntelliJ 2020.3.*

- .github/workflows/build.yml
- src/main/kotlin/io/snyk/plugin/services/SnykCliService.kt
- src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt
- src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
This PR fixes the issue when scanning directory is specified via additional parameters.
> fix: move 'test' parameter as first argument

- CHANGELOG.md
- README.md
This PR updates readme with links to all CLI supported managers.
> docs: replace supported package managers list with a link in readme

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/services/SnykCliService.kt
- src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt
This PR fixes handling custom endpoint (`--api`) option. The behavior was changed in CLI (https://github.com/snyk/snyk/blob/master/src/lib/config.ts#L10), it should be capitalized or use envvar.
> fix: handle custom endpoint option correctly

- gradle.properties
This PR bump `pluginVersion` to 2.1.1 (next release tag).
> chore: bump plugin version to 2.1.1

- CHANGELOG.md
- gradle.properties
This PR updates untilVersion to 211 to make plugin compatible with 2021.1.
> chore: update until version to 211

- CHANGELOG.md
- build.gradle.kts
- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
- src/main/kotlin/io/snyk/plugin/services/SnykCodeService.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/HashContentUtils.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeIgnoreInfoHolder.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeUtils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/OnboardPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/resources/full.dcignore
- src/test/kotlin/io/snyk/plugin/snykcode/core/IgnoreInfoHolderPlatformTestCase.kt
- to fully match https://git-scm.com/docs/gitignore#_pattern_format and glob syntax rules (https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-);
- caches invalidation and re-parsing on those files change;
- generic .dcignore added on project opening if no .gitignore/.dcignore exist;
- functional tests for IgnoreInfoHolder related basic functionality.
> fix: .dcignore and .gitignore parsing and usage (ROADRUNNER-55)

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/FileTreeNode.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeNode.kt
UI presentation fix: Show OSS results as `obsolete` when it's outdated
> fix: mark obsolete CLI result when cache dropped [ROADRUNNER-120]

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeParams.kt
This PR respects 'ignore unknown CA' option (sams as `--insecure` for CLI) for Snyk Code API client.
Related PR: https://github.com/snyk/code-sdk-java/pull/24
> fix: consider 'ignoreUnknownCA' option for Snyk Code API client

- build.gradle.kts
This PR pins the segment library version to 3.1.0, since this version has Retrofit2 support.
Related to https://github.com/segmentio/analytics-java/issues/218
> chore: specify exact version of segment library to 3.1.0

- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
This PR fix the issue with infinite loop to ask API for enabling/disabling SAST feature. Maximal attempt count is 20.
> fix: set maximal attempts for ask for sast feature

- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/net/SnykApiClient.kt
- src/main/kotlin/io/snyk/plugin/services/SnykAnalyticsService.kt
- src/main/kotlin/io/snyk/plugin/services/SnykApiService.kt
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
- src/main/kotlin/io/snyk/plugin/ui/actions/SnykTreeScanTypeFilterAction.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
- src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- Should fix https://snyk.zendesk.com/agent/tickets/10881
- Explicit notification to the user in case of connection/network errors
- Unification for option/condition checks:
- ~~Change sastEnable check from check in loop to explicit user's check to avoid servers overload and time outing for slow users~~ loop start only after link to SnykCode option web page opened
- Change "endpoint support" check from endpoint field listener to explicit user's check to avoid collisions with other checks
> fix: network related exceptions and notifications. Related to [ROAD-35]

- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/OnboardPanel.kt
Depending on sastEnable flag on server user will see:
> fix: welcome(onboarding) screen simplification by removing interactive alerts [ROAD-164]

- src/main/kotlin/io/snyk/plugin/events/SnykSettingsListener.kt
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/OnboardPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
fix: welcome and auth screen was missed to display if toolWindow was closed when project opening
fix: Run action availability before auth passed
> fix: welcome and auth screen was missed to display [ROAD-175]

- build.gradle.kts
This PR bumps the `org.jetbrains.intellij` plugin to 0.4.22 and disables auto-reload plugin in dev mode.
p.s.: we update patch version 0.4.21 -> 0.4.22 and consider major version upgrade in separate PR.
> chore: update org.jetbrains.intellij plugin to 0.4.22

- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
- src/main/kotlin/io/snyk/plugin/net/TokenInterceptor.kt
- src/main/kotlin/snyk/PluginInformation.kt
- src/test/kotlin/snyk/advisor/api/AdvisorApiClientTest.kt
This PR extract getting plugin information logic into `PluginInformation.kt` class.
We'll need this information by setting:
- envvars
- user-agent header
- sentry alerting (later)
> chore: move getting plugin info into utility class

- .github/workflows/build.yml
- .github/workflows/detekt.yml
- .github/workflows/release.yml
- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/io/snyk/plugin/services/SnykAnalyticsService.kt
This PR update `pluginUntilBuild` version to `212.*`.
For compatibility reasons:
- update gradle version to `6.9`
- update `org.jetbrains.changelog` plugin version to `1.2.1`
- update `org.jetbrains.intellij` version to `1.1.2`
> chore: compatibility with IntelliJ 2021.2 platform

- src/integTest/kotlin/snyk/oss/OssServiceTest.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
- src/main/kotlin/snyk/oss/OssService.kt
fix: empty oss-cli output case;
fix: miss-formed oss-cli JSON output case;
feat: log all notification shown to user.
PS should fix #153
> fix exceptions when parsing OSS CLI output [ROAD-250]

- src/main/kotlin/io/snyk/plugin/analytics/Iteratively.kt
- src/main/kotlin/io/snyk/plugin/services/SnykAnalyticsService.kt
This PR extracts calling `Itly.getInstance().load` method into singleton object `Iteratively`.
The fix is needed because sometimes IntelliJ creates light services from different classloaders.
> fix: prevent multiple execution of Iteratively load method [ROAD-296]

- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/snyk/amplitude/AmplitudeExperimentService.kt
This PR adds a settings to show scanner reminder only once (since it's not possible to set it from Amplitude side).
> fix(experiment): add setting to show scanner reminder only once

- build.gradle.kts
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/snyk/PropertyLoader.kt
- src/main/kotlin/snyk/errorHandler/SentryErrorReporter.kt
- src/main/kotlin/snyk/errorHandler/SnykErrorReportSubmitter.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/application.properties
This PR implements the extension point `com.intellij.errorHandler` to integrate the plugin with the IDE's dialog to report fatal errors.
<details>
<summary>Click to see example screenshots</summary>
</details>
> feat: implement Sentry error reporter as error submitter [ROAD-261]

- .github/workflows/release.yml
This PR sets Sentry environment ("PRODUCTION") when running `release` GH workflow.
Otherwise it will be "DEVELOPMENT".
> fix: set production Sentry environment when running release workflow

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/OnboardPanel.kt
This PR removes usage of deprecated `withLeftGap()` method.
*Note for reviewers*: check plugin verifier logs to be sure no warnings are reported.
> fix: remove deprecated methods [ROAD-334]

- src/integTest/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandlerIntegTest.kt
- src/integTest/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandler.kt
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandlerTest.kt
Moved CLI download retry logic into background thread
> fix: 🐛 Network shouldn't be accessed in EDT or inside read action

- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
- src/main/kotlin/snyk/iac/IacIssue.kt
- src/main/kotlin/snyk/iac/IacSuggestionDescriptionPanel.kt
- src/main/kotlin/snyk/iac/IgnoreButtonActionListener.kt
- src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt
- src/test/kotlin/snyk/iac/IacSuggestionDescriptionPanelTest.kt
- src/test/kotlin/snyk/iac/IgnoreButtonActionListenerTest.kt
IaC ignoring: 
- mark node as `ignored` in the tree and make `ignore` button remain disabled in the description panel after issue reselection
- remove ignored issue from annotator's highlighting
Before ignoring:
After ignoring:
> fix: IaC ignored issue mark in the tree and ignore button enablemnt [ROAD-502]

- .github/detekt/detekt-config.yml
- build.gradle.kts
- src/integTest/kotlin/io/snyk/SnykBulkFileListenerTest.kt
- src/integTest/kotlin/snyk/container/KubernetesImageCacheIntegTest.kt
- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/snyk/container/KubernetesImageCache.kt
- src/main/kotlin/snyk/container/KubernetesWorkloadImage.kt
- src/main/kotlin/snyk/container/YAMLImageExtractor.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/snyk/container/YAMLImageExtractorTest.kt
- uses BulkFileListener to listen to file events
- uses Kubernetes Java Client to parse into Kubernetes Objects
- provides several functions in KubernetesImageCache.kt to access found files and image information
- interpolation of variables is not supported by Kubernetes, so we do not need to handle it
feat: ✨ add kubernetes java api dependency
> feat: ✨ detect Kubernetes files and extract image information from workload objects [ROAD-450]

- build.gradle.kts
- src/integTest/kotlin/io/snyk/SnykBulkFileListenerTest.kt
- src/integTest/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandlerIntegTest.kt
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/integTest/kotlin/snyk/iac/annotator/IacBaseAnnotatorCase.kt
- src/integTest/kotlin/snyk/iac/annotator/IacHclAnnotatorTest.kt
- src/integTest/kotlin/snyk/iac/annotator/IacJsonAnnotatorTest.kt
- src/integTest/kotlin/snyk/iac/annotator/IacYamlAnnotatorTest.kt
- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/cli/CliResult.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
- src/main/kotlin/snyk/iac/IacIssue.kt
- src/main/kotlin/snyk/iac/IacIssuesForFile.kt
- src/main/kotlin/snyk/iac/IacResult.kt
- src/main/kotlin/snyk/iac/IacScanService.kt
- src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt
- src/main/kotlin/snyk/oss/OssResult.kt
- src/main/kotlin/snyk/oss/OssService.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/LabelProviderTest.kt
- src/test/kotlin/snyk/amplitude/api/AmplitudeExperimentApiClientTest.kt
- src/test/kotlin/snyk/errorHandler/SentryErrorReporterTest.kt
- src/test/kotlin/snyk/iac/IgnoreButtonActionListenerTest.kt
- src/test/kotlin/snyk/net/HttpClientTest.kt
- changed FileListener to only update the node
- changed scan trigger to not check for description == null (please explain if this had a reason). When a user explicitly triggers a scan, we should not ignore it, I think.
> feat: ✨ only mark iac files obsolete if they have been changed [ROAD-570]

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
This pulls in the latest code-api and prepares the 2.4.8 release as a bugfix release. The build will only succeed after the new version 2.2.1 is available in maven central (see https://github.com/snyk/code-sdk-java/pull/29).
> fix: chore: ⬆️ upgrade Snyk Code Client to 2.2.1

- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
ConsoleCommandRunnerTest accidental dependency on pre-existing CLI file - lead to flaky tests on CI: https://github.com/snyk/snyk-intellij-plugin/runs/4533899699?check_suite_focus=true
> fix: ConsoleCommandRunnerTest accidental dependency

- src/integTest/kotlin/io/snyk/SnykBulkFileListenerTest.kt
- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceHeavyTest.kt
- src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/settings/ScanTypesPanelTest.kt
- src/integTest/kotlin/snyk/container/KubernetesImageCacheIntegTest.kt
- src/integTest/kotlin/snyk/iac/IacServiceTest.kt
- src/integTest/kotlin/snyk/oss/OssServiceTest.kt
- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandler.kt
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeIgnoreInfoHolder.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/OnboardPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindow.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
- src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanelTest.kt
For all our project services create correspondent funs in Util and check there if project is disposed return Null otherwise the service instance.
Then we need to remember to use any such service from correspondent fun only. 
Also Null case need to be handled in each particular case (in most places it looks like just ?. usage needed).
> fix: AlreadyDisposedException due to Project disposal before using project's service [ROAD-606]

- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeIgnoreInfoHolder.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/snyk/container/YAMLImageExtractor.kt
fix: exceptions in PsiManager.findFile() should be ignored (`null` returned as if PsiFile just not found) and not break the flow.
PS See Sentry's exception reports for examples.
> fix: exceptions from PsiManager.findFile()

- .editorconfig
- .github/workflows/release.yml
- .github/workflows/weekly-release.yml
- build.gradle.kts
- gradle.properties
Automatically determine the right semantic version from git history, create a tag and push to origin with the next version when e.g. `./gradlew release -Prelease.versionIncrementer=incrementMajor` is executed. Executing just `./gradlew release` will increase patch level, using `./gradlew release -Prelease.versionIncrementer=incrementMinor` will [increment](https://axion-release-plugin.readthedocs.io/en/latest/configuration/version/) the middle number. This all is done using the [axion release plugin](https://github.com/allegro/axion-release-plugin). This way, we do not need to manually set the version in gradle.properties. Developer releases on branches use `-SNAPSHOT` convention, e.g. `2.4.9-SNAPSHOT`.
Automatically create github release when release workflow is triggered, done using the …
> Facilitate Release Process

- src/integTest/resources/advisor-build-files/package.json
A security researcher found the "fake_pa" pkg was unclaimed.
They claimed the pkg and demoed RCE when npm install consumed the modified
package.json.
> fix: remove unclaimed malicious package

- .github/workflows/release.yml
Enabled once more in release workflow, after having updated the token. 
Right now, I haven't found a way to create an org-token or service account, so it is using a personal token tied to my account, limited to `project:releases` scope (according to https://docs.sentry.io/api/releases/create-a-new-release-for-an-organization/ that's enough).
> chore: enable sentry releases

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/SnykBulkFileListenerTest.kt
- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/snyk/iac/IacResult.kt
For our caches we need following events for file: Create, Change, Delete                               
Also in our caches we need next type of actions: _add_ _update_ _clean_                                
Note: Current implementation meaning:                                                                  
add - mark results as invalid anymore (i.e. next scan attempt should run scan and not use cache)      
update - mark item(file) result as obsolete (i.e. next scan attempt should run scan and not use cache)
clean - mark item(file) result as obsolete (i.e. next scan attempt should run scan and not use cache) 
BulkFileListener provide next events: Create, ContentChange, Move, Copy, Delete                        
Also in `before` state we have access to old files. …
> fix: caches update and cleaning [ROAD-646]

- CHANGELOG.md
- README.md
- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloader.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
Takes configuration from IntelliJ http proxy settings and uses it for CLI download, API calls, scans and authentication.
Can be verified using the VM:
https://github.com/bastiandoetsch/jvm-development-environment
> feat: ✨ use http proxy host and proxy port settings from IntelliJ proxy configuration

- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
fix: UI glitches due to Container's result/run-status checks absence;
feat: proper way to avoid IssueInTreeIsClicked events withing smartReloadRootNode()
> Container UI bugs and glitches

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
https://user-images.githubusercontent.com/20150761/153420414-789cfe6b-bf05-4442-8e20-f3232455ee4a.mov
> fix: caret is wrongly jumping to the last selected line in the Tree when editing file with issues.

- CHANGELOG.md
- src/main/kotlin/snyk/container/annotator/ContainerYamlAnnotator.kt
- src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt
original stacktrace:
```
ExternalToolPass: 
com.intellij.diagnostic.PluginException: annotator: snyk.iac.annotator.IacYamlAnnotator@75c76c6e (class snyk.iac.annotator.IacYamlAnnotator) [Plugin: io.snyk.snyk-intellij-plugin]
at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:272)
at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:221)
at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java …
```
> fix: write asynchronously in annotator, as it's might be a read action

- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/integTest/kotlin/snyk/iac/IacServiceTest.kt
- src/integTest/kotlin/snyk/oss/OssServiceTest.kt
- src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
- src/main/kotlin/snyk/oss/OssService.kt
This PR use CLI environment variable (`SNYK_CFG_DISABLE_ANALYTICS`) instead of CLI flag. The flag doesn't work for IaC and Container.
> fix: use environment variable when disabling usage analytics [ROAD-741]

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/TreePanel.kt
- src/main/kotlin/snyk/container/ContainerService.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt
fix: Container node still showing last results even if disabled
fix: Container node should handle case if no images in project found
fix: Container: invalid token shows error and don’t redirect to Auth panel
> fix: Container node UI bugs [ROAD-648] [ROAD-647] [ROAD-749]

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/SnykBulkFileListenerTest.kt
- src/integTest/kotlin/snyk/container/KubernetesImageCacheIntegTest.kt
- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/snyk/container/KubernetesImageCache.kt
- src/main/kotlin/snyk/container/YAMLImageExtractor.kt
Fix next bugs:
1. On full file content deletion caches are not updated.
2. On partial file content deletion KubernetesImageCache is not updated.
> fix: Container cache updates on full/partial file content deletion [ROAD-751]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/net/CliConfigService.kt
- src/main/kotlin/io/snyk/plugin/net/SnykApiClient.kt
- src/main/kotlin/io/snyk/plugin/services/SnykApiService.kt
- src/test/kotlin/io/snyk/plugin/net/CliConfigServiceTest.kt
- src/test/resources/test-fixtures/api-responses/snyk/sast_local-code-engine-disabled_200.json
This PR adds a feature to check SAST API endpoint with organization from settings (if configured).
Default value for org Retrofit query param is `null`. In this case Retrofit will omit URL query param.
> feat: sast settings with organization as url query param [ROAD-734]

- .github/workflows/release.yml
Changed the release action to a different one. Hard to test, but locally it looked good:
```
[Release/release] ⭐  Run Extract release notes
[Release/release]   ☁  git clone 'https://github.com/ffurrer2/extract-release-notes' # ref=v1
[Release/release]   🐳  docker cp src=/Users/bdoetsch/.cache/act/ffurrer2-extract-release-notes@v1/ dst=/var/run/act/actions/ffurrer2-extract-release-notes@v1/
[Release/release]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/ffurrer2-extract-release-notes@v1/] user= workdir=
[Release/release]   🐳  docker exec cmd=[node /var/run/act/actions/ffurrer2-extract-release-notes@v1/dist/index.js] user= workdir=
[Release/release]   💬  ::debug::changelog-file = 'CHANGELOG.md'
[Release/release]   💬  ::debug::release-notes-file = ''
[Release/release]   💬 …
```
> chore: fill github releases with changelog from changelog.md

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/snyk/SnykBundle.kt
- src/main/resources/SnykBundle.properties
This PR adds following features:
- providing hint for "Organization" settings (as context help label JB component)
- support for using message bundles (property files) => get rid of hard-coded text from source code
<details open>
<summary>General settings screenshot</summary>
</details>
> feat: show additional info for organization setting [ROAD-736]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
will fix [IncorrectOperationException](https://sentry.io/organizations/snyk/issues/3023294926/?referrer=slack)
> fix: Avoid IncorrectOperationException due to already disposed SnykTolWindowPanel when SnykAuthPanel invoked.

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/plugin/snykcode/core/IgnoreInfoHolderPlatformTestCase.kt
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/services/SnykCodeService.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeIgnoreInfoHolder.kt
will fix #173 and related `IOException: Permission denied` exceptions
> fix: generic .dcignore file creation failure and exceptions [ROAD-531]

- .snyk
- CHANGELOG.md
- build.gradle.kts
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeParams.kt
This PR enables HTTP request logging for the Snyk Code Client when the `SnykCode` logger is set to debug and enables to monitor / check API communication, thus.
- [ x ] Tests all succeed
- [ x ] Linted
- [ x ] CHANGELOG.md updated
- [ x ] README.md updated, if user-facing
> chore: enable request logging when SnykCode logger is in debug mode [ROAD-843]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
- src/test/kotlin/io/snyk/plugin/ui/UIUtilsTest.kt
will fix [IllegalArgumentException](https://sentry.io/organizations/snyk/issues/3211044785/?referrer=slack)
> fix: `IllegalArgumentException: wrong column` for issue's description panel creation

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
will fix [AlreadyDisposedException](https://sentry.io/organizations/snyk/issues/3211453802/?referrer=slack)
> fix: AlreadyDisposedException when annotations async refreshed for disposed project

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
Proxy credentials are part of the URI put into proxy environment variables. Thus, they need to be URL encoded.
> fix: 🐛 url-encode proxy credentials

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/plugin/TestUtils.kt
- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/integTest/kotlin/io/snyk/plugin/services/CliAdapterTest.kt
- src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- src/integTest/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloader.kt
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
- src/main/kotlin/io/snyk/plugin/ui/actions/SnykTreeScanTypeFilterAction.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/test/kotlin/io/snyk/plugin/TestUtils.kt
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt
- Honoring user's product selection on welcome screen before first ever scan
- Proper message when Code product is disabled due to unreachable org settings on backend
- Auth screen has priority to be shown in case of invalid/empty token
- Code scan endpoint url was internally corrupted after any Snyk settings change
chore: tests refactoring and improvement, also do only one actual CLI download test and use mocks in other tests
> fix: plugin first-time-run issues [ROAD-731]

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
Will fix [IllegalStateException](https://sentry.io/organizations/snyk/issues/3261803243/?referrer=slack)
> fix: Empty (or cancelled request for) proxy credentials

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt
- src/test/kotlin/snyk/common/IgnoreServiceTest.kt
will fix [IllegalStateException](https://sentry.io/organizations/snyk/issues/3267773115/?referrer=slack)
> fix: `IllegalStateException` when no `Document` found for invalid(obsolete) file

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt
It's a bug of UI presentation for correct underlying data, so UI tests are omitted and check done manually.
> fix: for Snyk Code multi-file issues code snippet in some data flow steps shown from wrong file [ROAD-846]

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
1. if no file supported by IaC is found, on click on the IaC root node in the tree, the vulnerability description panel should display the following text  (from CLI): `Could not find any valid IaC files`
2. if no file supported by OSS is found, on click on the OSS root node in the tree, the vulnerability description panel should display the following text (from CLI): `Could not detect supported target files in <project-path>.\nPlease see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.`
> feat: Show specific description when no IaC or OSS files found but corresponded scan performed [ROAD-644]

- CHANGELOG.md
- src/integTest/kotlin/snyk/container/ContainerBulkFileListenerTest.kt
- src/integTest/kotlin/snyk/oss/OssServiceTest.kt
- src/integTest/kotlin/snyk/oss/annotator/OSSGoModAnnotatorTest.kt
- src/integTest/kotlin/snyk/oss/annotator/OSSGradleAnnotatorTest.kt
- src/integTest/kotlin/snyk/oss/annotator/OSSMavenAnnotatorTest.kt
- src/integTest/kotlin/snyk/oss/annotator/OSSNpmAnnotatorTest.kt
- src/integTest/resources/oss-test-results/oss-result-package-no-remediation.json
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/ErrorTreeNode.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/NavigatableToSourceTreeNode.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionTreeNode.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeNode.kt
- src/main/kotlin/snyk/container/ui/ContainerImageTreeNode.kt
- src/main/kotlin/snyk/container/ui/ContainerIssueTreeNode.kt
- src/main/kotlin/snyk/iac/ui/toolwindow/IacIssueTreeNode.kt
- src/main/kotlin/snyk/oss/OssTextRangeFinder.kt
- src/main/kotlin/snyk/oss/OssVulnerabilitiesForFile.kt
- src/main/kotlin/snyk/oss/annotator/OSSBaseAnnotator.kt
- src/main/kotlin/snyk/oss/annotator/OSSGoModAnnotator.kt
- src/main/kotlin/snyk/oss/annotator/OSSGradleAnnotator.kt
- src/main/kotlin/snyk/oss/annotator/OSSMavenAnnotator.kt
- src/main/kotlin/snyk/oss/annotator/OSSNpmAnnotator.kt
- src/main/resources/META-INF/optional/withJava.xml
- src/main/resources/META-INF/optional/withKotlin.xml
fix: Open Source Scan results annotations are shown for Gradle(Groovy) dependencies;
feat: Navigation to the Editor for the Open Source Scan results and all failed artifact's scan results;
chore: refactoring to generalize/unify `Navigate to Source` for tree nodes.
> fix/feat/chore: navigation enhancement and annotation fixes [ROAD-567][ROAD-732]

- CHANGELOG.md
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/integTest/kotlin/snyk/container/ContainerBulkFileListenerTest.kt
- src/integTest/kotlin/snyk/container/ContainerServiceIntegTest.kt
- src/integTest/kotlin/snyk/container/annotator/BaseImageRemediationFixTest.kt
- src/integTest/kotlin/snyk/container/annotator/ContainerYamlAnnotatorTest.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/leaf/SuggestionTreeNode.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/secondlevel/SnykCodeFileTreeNode.kt
- src/main/kotlin/snyk/common/ProductType.kt
- src/main/kotlin/snyk/container/ContainerIssues.kt
- src/main/kotlin/snyk/container/ContainerService.kt
- src/main/kotlin/snyk/container/annotator/BaseImageRemediationFix.kt
- src/main/kotlin/snyk/container/annotator/ContainerYamlAnnotator.kt
- src/main/kotlin/snyk/container/ui/BaseImageRemediationDetailPanel.kt
- src/main/kotlin/snyk/container/ui/ContainerIssueDetailPanel.kt
- src/main/kotlin/snyk/container/ui/ContainerIssueTreeNode.kt
~~**!!! Could be reviewed/merged after #392 only !!!**~~ done
- Found Container vulnerabilities now grouped by ID (similar to OSS results):
- For images with no remediation/fix available issues count(grouped by severity) now shown too:
- Naming for scan results in the tree and naming of result's count is corrected.
- In the result's tree, second level nodes(file/image) now have number of vulnerabilities/issues found in it:
> Fix/container issues grouping by Id

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
By accident, a kotlin specific class was imported in to the Plugin Settings file.As not all IntelliJ-based IDEs bring Kotlin classes, the import led to a ClassNotFoundException and thus a plugin crash.
> fix: 🐛 dont use kotlin file, but java.io.File (fixes #403) [ROAD-1068]

- CHANGELOG.md
- src/integTest/kotlin/snyk/oss/OssServiceTest.kt
- src/main/kotlin/snyk/oss/OssService.kt
_This should add the `--all-projects` flag by default for the Rider IDE._
> fix: RIDER IDE now passes the --all-projects CLI arg by default [ROAD-1032]

- .github/workflows/build.yml
- .github/workflows/detekt.yml
This PR bumps environment to `ubuntu-latest` for all GitHub workflows.
The warning from actions:
> chore: use ubuntu-latest environment for all github workflows

- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/main/java/snyk/analytics/Identify.java
- src/main/kotlin/io/snyk/plugin/cli/CliError.kt
- src/main/kotlin/io/snyk/plugin/cli/CliResult.kt
- src/main/kotlin/io/snyk/plugin/services/CliAdapter.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/snyk/common/SnykError.kt
- src/main/kotlin/snyk/iac/IacError.kt
- src/main/kotlin/snyk/iac/IacResult.kt
Ignore IaC errors about broken JSON syntax
> Feat: ignore IaC errors about broken JSON files [ROAD-1201]

- CHANGELOG.md
- build.gradle.kts
- src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanelIntegTest.kt
- src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/integTest/kotlin/snyk/trust/WorkspaceTrustServiceTest.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykAuthPanel.kt
- src/main/kotlin/snyk/trust/TrustedProjects.kt
- src/main/kotlin/snyk/trust/WorkspaceTrustService.kt
- src/main/kotlin/snyk/trust/WorkspaceTrustSettings.kt
- src/main/resources/SnykBundle.properties
- src/test/kotlin/snyk/InMemoryFsRule.kt
- src/test/kotlin/snyk/trust/WorkspaceTrustServiceTest.kt
This PR adds a support for "Workspace Trust" feature. See screenshots section for UI.
All logic is located under `snyk.trust` package. It consists of following files:
- `TrustedProjects.kt` - responsible for showing modal dialog to a user before scanning. All UI-related work should be here.
- `WorkspaceTrustService.kt` - responsible for working with settings (persistence) and checking if paths are trusted or not. All logic should be placed here.
- `WorkspaceTrustSettings.kt` is a state file (xml section under `snyk.setting.xml`). It's only getters/setters for state, no logic or other code should be place there.
- new dependency (`testImplementation` scope) is added [Jimfs](https://github.com/google/jimfs). It's in-memory file system used in testing by checking trust paths (included or …
> feat: add workspace trust feature

- .github/detekt/detekt-baseline.xml
- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/net/RetrofitAuthenticator.kt
- src/test/kotlin/io/snyk/plugin/net/RetrofitAuthenticatorTest.kt
Prevents proxy authentication dialog popup, when proxy doesn't require auth.
```
WARN - #io.snyk.plugin.net.SnykApiClient - Failed to execute 'user/me' network request: auth must not be null
java.lang.IllegalStateException: auth must not be null
at io.snyk.plugin.net.RetrofitAuthenticator.authenticate(RetrofitAuthenticator.kt:22)
at okhttp3.internal.connection.RealConnection.createTunnelRequest(RealConnection.kt:519)
at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:258)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
```
> fix: authorization header for non-authenticated proxy 

- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/net/RetrofitClientFactory.kt
- src/main/kotlin/snyk/common/CustomEndpoints.kt
Plugin didn't find String extension functions `suffixIfNot` and `prefixIfNot`
This PR implements them in the plugin utils class as String extension functions.
> fix: NoClassDefinitionFound when kotlin libs not available

- src/integTest/resources/iac-test-results/fargate.json
- src/integTest/resources/iac-test-results/infrastructure-as-code-goof.json
Updating all URLs for IaC rules from https://snyk.io/security-rules to https://security.snyk.io/rules/cloud/, as all the rules are now hosted there. The old site is deprecated, and everything is redirected already to the new one.
> chore: update URL for Snyk IaC rule with new Site URL (APOLLO11-1173)

- .github/workflows/build.yml
_As part of the Snyk on Snyk initiative, we should add SCA monitoring to our CICD._
Output
```
Run snyk monitor --all-projects --exclude=integTest --org=7d7ab703-3630-4b46-afed-bad53a655ca3
snyk monitor --all-projects --exclude=integTest --org=7d7ab703-3630-4b46-afed-bad53a655ca3
shell: /usr/bin/bash -e {0}
env:
SNYK_TOKEN: ***
Monitoring /home/runner/work/snyk-intellij-plugin/snyk-intellij-plugin (snyk-intellij-plugin)...
Explore this snapshot at https://app.snyk.io/org/platform_hammerhead/project/4615ba08-519d-477a-9117-94d34d3fecd3/history/9e0e503e-5ab9-4918-9d13-b48505[2](https://github.com/snyk/snyk-intellij-plugin/actions/runs/5831859368/job/15816127239#step:4:2)20[7](https://github.com/snyk/snyk-intellij-plugin/actions/runs/5831859368/job/15816127239#step:4:8)70
Notifications about …
```
> chore: adds SCA monitoring to CICD

- .editorconfig
- .github/detekt/detekt-config.yml
- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
- src/main/kotlin/snyk/iac/IacIssuesForFile.kt
- src/main/kotlin/snyk/oss/OssVulnerabilitiesForFile.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/test/kotlin/snyk/oss/OssServiceTest.kt
Display up to 60 chars of the filepath in tree view
> feat: display up to 60 chars of the filepath in tree view

- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/snyk/common/lsp/commands/ScanDoneEvent.kt
- src/test/kotlin/io/snyk/plugin/analytics/AnalyticsScanListenerTest.kt
This PR changes the client side of the analytics to:
- change `deviceId` to `device_id`
- sync os and arch values to the ones used in LS and in VS
> feat: adjust to changed analytics interface [HEAD-921]

- .circleci/config.yml
- CHANGELOG.md
- catalog-info.yaml
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeFile.kt
The Kotlin library is not available on all Jetbrains IDEs, e.g. in PyCharm or Goland. This results in ClassNotFoundExceptions when using (extension) functions that are provided there.
Previously, we by accident referenced an extension function provided by the Kotlin library. This commit fixes this by defining a similar extension function `virtualFile.toPsiFile(project)` in the plugin code using `PsiManager.getInstance(project).findFile(virtualFile)`.
> fix: don't use extension function from kotlin intellij lib

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
The plugin code was using some code that was IJ/Kotlin specific. This PR removes it.
> fix: remove kotlin specific code that could fail in non-kotlin IDEs

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
- src/main/kotlin/io/snyk/plugin/analytics/AnalyticsScanListener.kt
- src/main/kotlin/io/snyk/plugin/services/SnykCliAuthenticationService.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/commands/ScanDoneEvent.kt
- src/test/java/snyk/common/lsp/LanguageServerWrapperTest.kt
- src/test/kotlin/io/snyk/plugin/analytics/AnalyticsScanListenerTest.kt
- src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- src/test/kotlin/io/snyk/plugin/services/download/SnykCliDownloaderServiceTest.kt
We have received several reports that CLI updates under Windows don't work. This is due to a file lock.
This PR ensures two things:
1. Independent of the number of projects, only one instance of the CLI is started in language server mode `snyk language-server` in the background.
2. CLI download, whether initial or an update, comes first, before the CLI is started in the background. This ensures the download does not run into a file lock under Windows.
Opened 5 projects, and verified only one snyk-win.exe process:
> fix: CLI update & download [IDE-123][IDE-124]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
Disabling automatic dependency management caused the scans not to work anymore
> fix: scans breaking, when CLI existent and downloads disabled

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
When closing a project, IntelliJ is calling all ProjectListeners registered. Snyk has its own, and on project close, clean up tasks are executed:
- remove the closed project from Snyk Code cache
- remove the closed projects source roots from language server workspace folders
The determination of the content roots of the closed project was running in the foreground, while the rest was already backgrounded.
This PR moves the determination of the content roots into a background thread, too. It also limits overall clean up execution time to 5s.
> fix: move everything to background thread when closing project [HEAD-1269]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/analytics/AnalyticsScanListener.kt
- src/main/kotlin/io/snyk/plugin/services/SnykCliAuthenticationService.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloader.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandler.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/leaf/SuggestionTreeNode.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykAuthPanel.kt
- src/main/kotlin/snyk/PluginInformation.kt
- src/main/kotlin/snyk/common/UIComponentFinder.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerSettings.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/trust/TrustedProjects.kt
- src/main/kotlin/snyk/trust/WorkspaceTrustService.kt
- src/test/java/snyk/common/lsp/LanguageServerWrapperTest.kt
- src/test/kotlin/io/snyk/plugin/TestUtils.kt
- src/test/kotlin/io/snyk/plugin/analytics/AnalyticsScanListenerTest.kt
- src/test/kotlin/io/snyk/plugin/extensions/SnykControllerImplTest.kt
- src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanelIntegTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- close down language server during download of CLI
- better messaging when CLI directory is not writeable
- use content roots for trust instead of the project, as project.basePath is not accurate for this.
> fix: close down language server during download, fix trust service [HEAD-1242][HEAD-1249]

- build.gradle.kts
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykCodeScanListenerLS.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SuggestionDescriptionPanelFromLS.kt
- src/main/kotlin/snyk/common/SnykCachedResults.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
Issue navigation didn't work correctly because of sorting of the issue map. Also, the dataflow was based on markers, which is not sufficient. Therefore it now takes the dataflow from language server (needs https://github.com/snyk/snyk-ls/pull/449).
This is a stacked PR on top of https://github.com/snyk/snyk-intellij-plugin/pull/474.
> fix: this fixes the dataflow and the issue navigation

- src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykCodeScanListenerLS.kt
- src/main/kotlin/snyk/common/SnykCachedResults.kt
> fix: cache cleaning and some name refactorings [IDE-134]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykCodeScanListenerLS.kt
This refactors the code-smell from #474. 
> refactor: remove code-duplication [IDE-134]

- CHANGELOG.md
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
Before, not answering a request message prompt from language server blocked subsequent interactions with language server. This fixes that.
> fix: (LS-Preview) do not hang on missing answers to message requests, timeout after 5s [IDE-161]

- CHANGELOG.md
- src/main/resources/META-INF/optional/withCsharp.xml
- src/main/resources/META-INF/optional/withGo.xml
- src/main/resources/META-INF/optional/withHTML.xml
- src/main/resources/META-INF/optional/withJava.xml
- src/main/resources/META-INF/optional/withJavaScript.xml
- src/main/resources/META-INF/optional/withKotlin.xml
- src/main/resources/META-INF/optional/withPHP.xml
- src/main/resources/META-INF/optional/withPython.xml
IntelliJ sometimes uses the annotator without explicit language definition (""), e.g for Java, but sometimes, e.g. for Kotlin, it needs a dedicated definition. This is just empirical on my machine, but as it doesn't cost much to define them, here they are.
> fix: make sure to have annotators available for languages [IDE-181]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/ScanState.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
Previously, when more than one project was opened, Snyk Code scans via Language Server were not working. This PR fixes that behaviour, by 
a) maintaining a content-root specific scan state and
b) triggering scans by content root
Content roots are mirrored in Language Server as WorkspaceFolders
> fix: (LS Preview) Snyk Code scans when having multiple projects open [IDE-160]

- CHANGELOG.md
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
Previously, the trust setting was not checked before triggering a scan. This PR fixes this.
> fix: check trust for content root before triggering Snyk Code scans

- CHANGELOG.md
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/resources/META-INF/optional/withCsharp.xml
- src/main/resources/META-INF/optional/withGo.xml
- src/main/resources/META-INF/optional/withHTML.xml
- src/main/resources/META-INF/optional/withJava.xml
- src/main/resources/META-INF/optional/withJavaScript.xml
- src/main/resources/META-INF/optional/withKotlin.xml
- src/main/resources/META-INF/optional/withPHP.xml
- src/main/resources/META-INF/optional/withPython.xml
- src/main/resources/META-INF/plugin.xml
Apparently specifying one annotator with language `""` is sufficient for any language. Also fixed late initialization of issues, to not be done in UI thread.
> fix: remove duplicated annotator definition [IDE-192]

- CHANGELOG.md
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/test/java/snyk/common/lsp/LanguageServerWrapperTest.kt
Previously, content roots were not normalized, so that duplications could occur, e.g. when a child root would be included, even though the parent was already there.
> fix: workspace folder and content root handling [IDE-204]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
Adds the `[ Ignored ]` text in front of ignored findings. It needs to be behind a feature flag because the backend will always return the ignore data, so the frontend needs to gate it.
In [this](https://snyk.slack.com/archives/C06LTKLFY2F/p1711376124767019) thread we decided not to show AI fixes if the finding is ignored.
> feat: mark findings as ignored in tree view [IDE-193]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykCodeScanListenerLS.kt
> fix: don't navigate to source on scan finished

- src/main/kotlin/io/snyk/plugin/Utils.kt
Our plugin triggered a reparse of project files for every save/change. This had a hefty performance penalty.
> fix: performance issue when using code vision

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloader.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandler.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SuggestionDescriptionPanelFromLS.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/test/kotlin/io/snyk/plugin/TestUtils.kt
- src/test/kotlin/io/snyk/plugin/extensions/SnykControllerImplTest.kt
- src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandlerIntegTest.kt
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderTest.kt
The LS Protocol version synchronizes feature sets between server and client outside of the LS capability mechanism. In order to download the right version of the CLI, the download process had to be adjusted to
- look up the right version at https://static.snyk.io/cli/latest/ls-protocol-version-{needed-protocol-version}
- extract the latest CLI version from there and 
- download it.
> feat: respect LS protocol version when updating CLI [IDE-157]

- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SuggestionDescriptionPanelFromLS.kt
Trim whitespaces in dataflow code lines
> fix: trim starting whitespaces in code lines [IDE-242]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/snyk/container/KubernetesImageCache.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/settings/ScanTypesPanelTest.kt
Ensures if the auto-scan functionality is enabled and the new Snyk Code LS feature is enabled we schedule a scan for all products. Also refactors a function name because it was a bit confusing in this context.
I've tested it by clearing out the scan results and running the sandbox IDE with `runIDE`:
- before this change there would still be no results
- after this change scans get triggered and new results appear
I don't see any unit tests for this file, so I didn't add any.
> feat: scan all products on startup if enabled [IDE-241]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/IssueViewOptionsPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/SeveritiesEnablementPanel.kt
At the moment when we change the scan type selection the Tree Nodes associated with them don't get re-enabled. This seems to be because the changes in the `ScanTypesPanel` don't actually get trickled up to `SnykProjectSettingsConfigurable` in order for the `apply()` method to run when `isModified()` returns `true`. The reason for this is that when the selections change the `Dialog.isModified()` function called in `isScanTypeChanged` in `SnykSettingsDialog` hasn't registered that there has been a change. We're now achieving that with the use of `bindSelected`.
We have some validation in place so that pre-apply we don't allow people to deselect all scan types. The new selections only get "persisted" globally once the `apply()` function gets called so the new action listener we added for …
> fix: settings for scan types

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/extensions/SnykControllerImpl.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
- src/main/kotlin/io/snyk/plugin/ui/settings/IssueViewOptionsPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt
When I implemented https://github.com/snyk/snyk-intellij-plugin/pull/510 I didn't realise that the LS actually has logic for scanning on startup. So because of that, we end up triggering multiple code scans and ending up in a loop because https://github.com/snyk/snyk-intellij-plugin/blob/5282559023d2d1987bd893ea78f1df585ff553e9/src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt ends up saving the docs and then triggering another scan for Snyk Code. 
The fix involves only triggering scan for non-Snyk Code when in LS on start-up. I've refactored the code a bit so that we are preparing ourselves for when we enable OSS and IaC in LS too for IntelliJ.
> fix: trigger scan on startup for non-code

- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/analytics/AnalyticsScanListener.kt
When LS is used for Snyk Code scanning, IntelliJ does not need to report analytics data,
as this is already handled after each scan by Language Server. Actually, it is duplicating the data.
This PR removes the listener that listens on Snyk Code via LS scan results.
> fix: don't send analytics events about snyk code when ff enabled

- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
Previously, the initialization of language server was triggered several times.
This PR adds 
- asserts that 
- content roots are only added after initialization
- initialization is not occurring recursively
- retry mechanism to add a project to language server waiting up to 30s when starting up
- a fix when initializing with an API error on the sastEnabled call
- logging when shutting down
> fix: sync when starting up language server in a multi-project setup

- CHANGELOG.md
- src/main/kotlin/snyk/common/CustomEndpoints.kt
In https://github.com/snyk/snyk-intellij-plugin/pull/515/ the `/v1` was appended in IntelliJ for all calls, even though there are some that don't need it. Only old v1 APIs need this path, otherwise we should leave it out. We noticed this problem by having the `snykCodeConsistentIgnores` feature flag enabled, which enables a flow that calls some other APIs.
In order for this to not introduce a new bug, we need https://github.com/snyk/snyk-ls/pull/498 to get merged first.
> fix: remove incorrect /v1 path [IDE-126]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
This PR uses the native Kotlin APIs to adapt to the IntelliJ theme settings maintaining visual consistency.
- Fetch theme-appropriate colors with `JBColor.namedColor` and `UIUtil` methods.
- Add `toCssHex` utility for converting Color objects to CSS HEX format to be injected into the JBCefBrowser.
|🌒 Dark|☀️ Light|🧛‍♀️ Darcula|
|-|-|-|
|![dark-theme](https://github.com/snyk/snyk-intellij-plugin/assets/1948377/e96443d5-d6b1-49ee-bcd4-c8420d4ec5cd)|![light-theme](https://github.com/snyk/snyk-intellij-plugin/assets/1948377/721bbe62-1947-453d-b03e-94474a11b439)|![darcula-theme](https://github.com/snyk/snyk-intellij-plugin/assets/1948377/46e9ba1b-c37b-497c-9c3a-4d4adbfa005d)|
> refactor: use native IntelliJ color properties for theme consistency [IDE-269]

- CHANGELOG.md
- src/main/kotlin/snyk/common/CustomEndpoints.kt
- src/test/kotlin/snyk/common/CustomEndpointsTest.kt
- src/test/kotlin/snyk/errorHandler/SentryErrorReporterTest.kt
Improves the validation so that only `http(s)://api.` APIs are configured in the custom endpoint field.
Tested manually by running the extension with the latest CLI.
> fix: custom endpoint validation and default [IDE-131]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/resources/META-INF/plugin.xml
Adds the registry flag to be used while integrating OSS into IntelliJ via LS. Also adds a small "fix" which means once we enable the LS we also check that OSS is enabled from the settings, like we do for Code too.
> feat: add oss ls registry flag [IDE-283]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykFile.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/events/SnykScanListenerLS.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/leaf/SuggestionTreeNodeFromLS.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/secondlevel/FileTreeNodeFromLS.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykCodeDataflowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykCodeExampleFixesPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykCodeOverviewPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SuggestionDescriptionPanelFromLS.kt
- src/main/kotlin/snyk/code/annotator/SnykAnnotator.kt
- src/main/kotlin/snyk/code/annotator/SnykCodeAnnotatorLS.kt
- src/main/kotlin/snyk/code/annotator/SnykOSSAnnotatorLS.kt
- src/main/kotlin/snyk/common/SnykCachedResults.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/main/kotlin/snyk/oss/OssBulkFileListener.kt
- src/main/kotlin/snyk/oss/annotator/OSSBaseAnnotator.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSCodeTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSOSSTest.kt
- src/test/kotlin/snyk/UIComponentFinder.kt
This PR loads the Tree Nodes for OSS from LS. It also renders a simple Suggestion Panel with a title and subtitle, but the follow-up UI elements will be added in a separate PR.
It has been written so that all the product lines loaded via the LS are rendered the same way. So the `ScanIssue` type now exposes functions that are meant to be used in the UI elements to render information about the issue, depending on what product-line it is.
It requires the changes in https://github.com/snyk/snyk-ls/releases/tag/v20240513.094925 to work, so update the CLI locally for now and run `make build`, then change the path to the CLI in the Snyk Settings. Also make sure to enable the `snyk.preview.snyk.oss.ls.enabled` registry flag in IntelliJ.
Without feature flag:
With feature flag:
> feat: load Snyk OSS issues in the Tree view via LS [IDE-238]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykOSSDetailedPathsPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykOSSIntroducedThroughPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SnykOSSOverviewPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SuggestionDescriptionPanelFromLS.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSCodeTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSOSSTest.kt
This PR is a continuation of https://github.com/snyk/snyk-intellij-plugin/pull/525 and loads the full OSS content inside the Suggestion Panel. The components were taken from https://github.com/snyk/snyk-intellij-plugin/blob/fa6d6e06028ebf45c3b056fb67b3fbf26b630e41/src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/VulnerabilityDescriptionPanel.kt. I could have de-duplicated them but we want to remove this file anyway soon and it would require retro-fitting the data types into the `IssueData` type for the LS so a bit more effort than worth it.
It requires the changes in https://github.com/snyk/snyk-ls/releases/tag/v20240513.094925 to work, so update the CLI locally for now and run `make build`, then change the path to the CLI in the Snyk Settings. Also make sure to enable the …
> feat: load Snyk OSS issues in the suggestion panel via LS [IDE-238]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/snyk/common/CustomEndpoints.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/test/kotlin/snyk/common/CustomEndpointsTest.kt
Currently when using the `stable` CLI version in IntelliJ (with or without the "Code in LS" registry flag enabled) we end up failing to run Snyk Code scans because the call to retrieve the SAST settings requires a `/v1` in the path. This has started since https://github.com/snyk/snyk-intellij-plugin/pull/515. 
In https://github.com/snyk/snyk-intellij-plugin/pull/523 we removed this from being added to all API calls because of some bugs we noticed at the time. The bug at the time was that when `snykCodeConsistentIgnores` is enabled, we make some calls to the new Snyk REST API so we should not add this `/v1` to all calls. In https://github.com/snyk/snyk-ls/pull/498 (requirement for PR#523), we made sure to only add `/v1` to the required calls but this missed the cutoff for the first …
> fix: append v1 suffix conditionally

- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
Previously, LS was always logging in debug mode. Now it is respecting the logger settings.
> fix: disable debug logging by default for ls

- .gitignore
- CHANGELOG.md
- build.gradle.kts
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/stylesheets/SnykStylesheets.kt
- src/main/resources/stylesheets/snyk_code_suggestion.scss
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSCodeTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSOSSTest.kt
Extracts custom IntelliJ styling from `snyk-ls` and injects it into the HTML after compiling `.scss` file to `.css` using https://github.com/EtienneMiret/sass-gradle-plugin. This requires https://github.com/snyk/snyk-ls/pull/522 so that `${ideStyle}` is available.
To test:
- Run `make build-debug` in `snyk-ls` in the branch from https://github.com/snyk/snyk-ls/pull/522
- Run `make build` in the CLI after adding a replace directive for `snyk-ls`
- Run the sandbox using `runIde`
- Replace the CLI path in the sandbox to the path for the local CLI and disable automatically managing the binaries
- Make sure to use an org that has the `snykCodeConsistentIgnores` FF enabled (e.g. `ide-consistent-ignores-test`)
- Navigate to a Snyk Code vulnerability
Without the LS change:
With the LS change:
> feat: inject custom styling [IDE-240]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/secondlevel/InfoTreeNode.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSlTest.kt
This adds some warning messages in the Tree View that are already in VSCode for the following cases:
- no vulns found
- the number of vulns found
- the number of vulns that can be fixed by DeepCode AI
It also adds info about the number of ignored issues, so they are made aware of that.
Compared to https://github.com/snyk/vscode-extension/pull/464, we won't show the warnings if all the issue view options are unselected. That is because we don't allow customers to unselect all of them.
> feat: show count of ignored and non-ignored issues [IDE-332]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
- src/main/resources/stylesheets/snyk_code_suggestion.scss
Adds some simple JavaScript to hide the AI fixes panel in IntelliJ for now since we're missing styling and interactions and instead to show the dataflow panel and example commit fixes. There are many ways we could do this, and probably better, but we will make this panel functional soon so I went for the quickest solution.
It needs https://github.com/snyk/snyk-ls/pull/527 for testing.
The backend isn't working at the moment so for testing I used an org that doesn't have the feature flag enabled and had to change a small part of the code so it's loading the HTML panel:
```
diff --git a/src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt b/src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
index 5a11c26b..d6c486ad 100644
--- …
```
> feat: hide ai fix panel and add more styling overrides [IDE-272]

- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
Environment Name/Version set by the IntelliJ Plugin. I couldn’t find the problem and it was not always reproducible but it showed like the below:
`"environment": {"name":"GOLAND/2023.3.4 (Mac OS X;aarch64) JETBRAINS_IDE/2.8.1 (GOLAND/2023.3.4)","version":"lsp4j"}`
The name should just be GOLAND and the version should be 2023.3.4  not lsp4j.
> fix: Update Integration Environment and Version

- CHANGELOG.md
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
> fix: dont use kotlin specific convenience function

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
- src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeBulkFileListener.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/snyk/amplitude/api/AmplitudeExperimentApiClient.kt
- src/main/kotlin/snyk/common/AnnotatorCommon.kt
- src/main/kotlin/snyk/common/SnykCachedResults.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/iac/IacResult.kt
- src/main/kotlin/snyk/trust/TrustedProjects.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/test/kotlin/snyk/common/lsp/LanguageServerWrapperTest.kt
- src/test/kotlin/snyk/common/lsp/SnykLanguageClientTest.kt
- don't display IaC ignored errors in balloon notification
- don't process directories in file listener
- don't output amplitude connection problems as error in logs
- add disposal handling
- add dumb mode (don't run during indexing) handling
- added a few unit (not integration) tests
This fixes https://plugins.jetbrains.com/plugin/10972-snyk-security/reviews#review=101648 (at least the display)
You can see, no balloon notification:
> fix: don't display IaC ignored errors in balloon notification

- src/main/resources/stylesheets/snyk_code_suggestion.scss
Increases the font size in the tabs so it matches the [designs](https://www.figma.com/design/hcI2QHUtHfcIjgrpYlMqff/Holistic-Ignores?node-id=2292-63654&t=iIxZM8o3pih8EY4M-0) more.
> fix: tab font size for consistent ignores [IDE-382]

- src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
- src/main/resources/stylesheets/snyk_code_suggestion.scss
In the HTML template served by LSP, we have defined two SVG icons for the arrow navigation: one is shown for light themes the the other is shown for dark themes. To be able to toggle between them, we take advantage of the class names added by VSCode: `vscode-dark` and `vscode-light`. The work that enables this is [here](https://github.com/snyk/vscode-extension/pull/472).
This PR for IntelliJ follows this same idea: we added the CSS rules to be applied depending on the IDE theme selection. We do so by defining `.dark-only`, `.light-only` and `high-contrast` rules and they get applied by manipulating the DOM adding the correct class name to the body of document.
This PR also fixed the code diff colour for high contrast themes.
Related to the migration from tab-based to arrow-based …
> refactor: CSS rules to support IDE themes for Code Issue panel [IDE-294]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/snyk/common/CustomEndpoints.kt
- src/test/kotlin/io/snyk/plugin/UtilsKtTest.kt
- src/test/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/test/kotlin/snyk/common/CustomEndpointsTest.kt
- Converts the old endpoint syntax to the new and saves it in the settings. Also saves the default endpoint explicitly, if no endpoint is given.
- Adds tooltips to explain the right endpoint format and other settings.
- Adds a validation to not enter `-d` as additional parameter, which is not supported by IntelliJ
> fix: automatically migrate old endpoint [IDE-407]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
- src/test/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGeneratorTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSOSSTest.kt
The change in this PR is to load the virtual file from the `filePath` in the component instead of using the provided virtual file. This way we can navigate to lines in other files that are not the originating file of the issue.
There are some linting changes too, after configuring the default linter in IntelliJ to format on save.
https://github.com/snyk/snyk-intellij-plugin/assets/81559517/042ca443-238c-4be2-871b-bf9d64896f2c
> fix: dataflow links work across files [IDE-391]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt
Fixes the count of issues and ignored issues in the Tree View so that when the Issue View Options change the counts don't change, only the rendered issues do.
Also adds a missing warning that I should have added as part of https://snyksec.atlassian.net/browse/IDE-332 where there are no ignored issues and only showing ignored issues or there are no open issues and only showing open issues.
I enabled the default linter in IntellJ and it formatted a file. Let me know if you'd like me to undo that.
> fix: ignore counts in info tree node [IDE-413]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt
We want to include ignored issues in the fixable issues count. Also, turns out that the info node for AI fixes wasn't being rendered anyway because of how the `addInfoTreeNode` function was called, which means that `fixableIssuesCount` was null`.
> fix: include ignored issues in AI fix count [IDE-346]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/Utils.kt
- src/main/resources/stylesheets/snyk_code_suggestion.scss
Changes some colours in order to match the [designs](https://www.figma.com/design/hcI2QHUtHfcIjgrpYlMqff/Holistic-Ignores?node-id=2292-61688&t=larzTCeHFfRtz6av-0)
Make sure to run https://github.com/snyk/snyk-ls/pull/552 first if you want to call out any inconsistent UI elements, in case they're already addressed there.
> fix: colours, font family, and font size for consistent ignores [IDE-386]

- .circleci/config.yml
Add release-branch parameter to security-scans, as the default one is set to "main"
> chore: add release branch for prodsec security scan (non default)

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/snyk/common/SnykCachedResults.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
When failing scans via the LS we forgot to render the error state. So this PR does that and also makes sure the error state is persisted in-between changes of the settings.
There are some linting changes too.
To test this, I used `juice-shop` since for some reason it fails when I try to scan it using OpenSource in prod. Then:
- I trigger a scan and notice the new `(error)` string appended to the open source tree node
- I enable Container scans and notice that the `(error)` string does not disappear
- I trigger a new scan and notice the `(error`) string temporarily gets replaced by the `(scanning...)` string
> fix: render error after failed ls scan [IDE-401]

- CHANGELOG.md
- src/main/kotlin/snyk/code/annotator/CodeActionIntention.kt
- src/main/kotlin/snyk/code/annotator/SnykAnnotator.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerSettings.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
This PR enhances the existing `codeActions` returned via the LS for OSS with quickfix actions that tell us what version to upgrade a package to. 
The only difference is that the new "OSS via LS" code actions have Snyk Learn actions too and we return quickfix code actions for all possible upgrade paths, rather than just the one.
To review, build https://github.com/snyk/snyk-ls/pull/511 and follow the review instructions there.
🚨After having merged, please update the CLI go.mod to pull in latest language server.
This was tested by building `snyk-ls` from https://github.com/snyk/snyk-ls/pull/511 and then the CLI with a `snyk-ls` replace directive, then changing the IntelliJ sandbox generated from this branch to point at the local CLI. Make sure to enable the registry flag.
The tests were run …
> feat: code action for OSS via LS in IntelliJ [IDE-284]

- .github/workflows/detekt.yml
- .github/workflows/readme-sync.yml
- CHANGELOG.md
- README.md
This PR upgrades the `github/codeql-action/upload-sarif` action from **v1** to **v3** in our GitHub Actions workflow. This change is necessary because the v1 version of the **CodeQL** Action was deprecated on December 2024, and is no longer supported or updated.
Additionally, this PR includes a conditional check to ensure that `` and `` markers are present in the `README.md` file. These markers are needed for the `patchPluginXml` task in the Gradle script to run correctly.
> fix: upgrad `github/codeql-action/upload-sarif` to v3 in GHA workflow [IDE-479]

- CHANGELOG.md
- build.gradle.kts
- src/main/kotlin/snyk/oss/OssService.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
- src/test/kotlin/snyk/oss/OssServiceTest.kt
> fix: add `--all-projects` for all jetbrains versions

- CHANGELOG.md
- src/main/kotlin/snyk/container/ContainerBulkFileListener.kt
- src/main/kotlin/snyk/iac/IacBulkFileListener.kt
- src/main/kotlin/snyk/oss/OssBulkFileListener.kt
This PR adds support for handling `.snyk` file. It relates to the changes made in the Language Server (PR: https://github.com/snyk/snyk-ls/pull/563), where logic for handling `textDocumentDidSaveHandler` events for `.snyk` files was added.
When a `.snyk` file changes, the all the products cache will be dropped triggering a re-scan.
- Language Server PR: https://github.com/snyk/snyk-ls/pull/563
https://github.com/snyk/snyk-intellij-plugin/assets/1948377/021fd2ac-8845-4c6d-adcb-87e85de1127c
> feat: add support for `.snyk` file for OSS, Container and IaC products [IDE-253]

- CHANGELOG.md
- src/main/kotlin/snyk/oss/OssBulkFileListener.kt
Formatting mostly (because of the linter), the only actual change is line 99.
> fix: invalidate oss cache in ls when files change

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/ThemeBasedStylingGenerator.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/main/kotlin/stylesheets/SnykStylesheets.kt
- src/main/resources/stylesheets/snyk_oss_suggestion.scss
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSCodeTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSOSSTest.kt
Adds some styling so that the new HTML panel and the native panel look more or less the same. The only noticeable differences are:
- The text in the `Detailed paths` changed from `Fix` to `Remediation`
- The font for the code, which now matches the one chosen by the customer
- The labels don't have a colon anymore, which matches what we see in VSCode too (could add the colons back if needed via CSS)
Refactors the code a bit too so that we can re-use more of it for both Snyk Code and Snyk OSS.
Needs https://github.com/snyk/cli/pull/5356 for testing.
Native:
HTML:
> feat: load html for oss in ls [IDE-285]

- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/snyk/common/SnykCachedResults.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
Propagate scan error from LS to IntelliJ and display it.
> fix: better error handling for OSS scans via LS [IDE-486]

- src/main/kotlin/io/snyk/plugin/ui/jcef/ThemeBasedStylingGenerator.kt
- src/main/resources/stylesheets/snyk_code_suggestion.scss
- src/main/resources/stylesheets/snyk_oss_suggestion.scss
This PR fixes the `font-size`and `font-family` accordantly to Snyk Design System to keep the look and feel of products and experiences consistent.
> [!NOTE]  
> This change needs to be tested together with the Language Server https://github.com/snyk/snyk-ls/pull/627
|Before|After|
|-|-|
|<img width="1488" alt="before-code" src="https://github.com/user-attachments/assets/6ede524d-f51c-4d71-adf8-234987b8ed3b">|<img width="1479" alt="after-code" src="https://github.com/user-attachments/assets/12490299-d04c-4076-803a-3ce27881a76b">|
> fix: `font-family` and `font-size` are set from Language Server

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykFile.kt
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
- src/main/kotlin/snyk/code/annotator/SnykOSSAnnotator.kt
- src/main/kotlin/snyk/common/EnvironmentHelper.kt
- src/main/kotlin/snyk/common/lsp/LSCodeVisionProvider.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderTest.kt
- fixes the missing flash icon in the Open Source tree when packages can be upgraded automatically
- remove incorrect guard in code vision provider
- added name/description in code vision setting
- use intellij determined environment variables when starting up language server
- fixes a snyk file bug that seems to come from IntelliJ (icon usage)
- fixes display of base branch per project
> feat: use intellij environment in ls startup

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/ui/BranchChooserComboboxDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/secondlevel/InfoTreeNode.kt
- src/main/kotlin/snyk/common/annotator/SnykAnnotator.kt
- src/main/kotlin/snyk/common/lsp/FolderConfigSettings.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/test/kotlin/io/snyk/plugin/ui/BranchChooserComboBoxDialogTest.kt
- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt
- src/test/kotlin/snyk/container/ContainerBulkFileListenerTest.kt
Adds a tree node for each content root in each scan type that allows selection of a reference branch, if delta findings is enabled. 
Open Todo: wait for the setting to be available, to check against the real setting instead of setting delta findings to true in the UI.
> feat: add dialog to choose reference branch [IDE-601]

- CHANGELOG.md
- src/main/kotlin/snyk/common/annotator/SnykAnnotator.kt
- src/main/kotlin/snyk/common/annotator/SnykLineMarkerProvider.kt
- src/main/resources/META-INF/plugin.xml
This adds an option to enable/disable Snyk gutter icons in the IntelliJ Gutter Icons Editor settings page.
> feat: add option to enable/disable gutter icons

- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
- src/main/kotlin/io/snyk/plugin/ui/BranchChooserComboboxDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/ApplyFixHandler.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/GenerateAIFixHandler.kt
- src/main/kotlin/snyk/common/codevision/LSCodeVisionProvider.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/test/kotlin/snyk/common/lsp/LanguageServerWrapperTest.kt
Previously, at startup, two scans were triggered due to LS triggering one automatically during startup and IntelliJ triggering one manually on opening a project.
Now, no scan is manually triggered when opening a project.
In addition to using the feature flag API endpoint, consistentIgnores status is now detected when processing scan results. When an issue is ignored, this can only come from the feature being on, so it's switched on in IntelliJ. This should make sure that whenever ignored issues are transmitted, IntelliJ filters & displays them correctly.
Fixes code vision not displaying.
> fix: don't double scan on startup, handle feature flags better

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerBulkFileListener.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/main/kotlin/snyk/sdk/SdkHelper.kt
- src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
SDKs are now reported to LS when it asks.
> feat: use configured sdk in language server [IDE-688]

- .snyk.env.darwin
- CHANGELOG.md
- CONTRIBUTING.md
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- cuts max message length
- ensures ls is initialized when adding content root
- adds default java home/path extension via config file
> fix: cut max message length, ensure ls init

- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloader.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerRestartListener.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/progress/ProgressManager.kt
- src/test/kotlin/snyk/common/lsp/SnykLanguageClientTest.kt
- register download listener
- on successful download:
- stop all scans
- cancel all progresses
- shutdown
- sleep for a second
- restart Language Server
- connect all workspace folders to newly started LS
> fix: improve download and restart logic

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerBulkFileListener.kt
Spaces in folder or file names could not be found by IntelliJ SDK, as the findbyURL method does not decode HTML encoded spaces. This PR changes this to use the findByNIOPath method to get the virtual file and converts the URI instead.
> fix: allow spaces in folder and files names [IDE-684]

- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/main/kotlin/snyk/common/lsp/commands/Commands.kt
> feat: load issue html on demand

- CHANGELOG.md
- src/main/kotlin/snyk/common/CustomEndpoints.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/test/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
- src/test/kotlin/snyk/common/CustomEndpointsTest.kt
- src/test/kotlin/snyk/common/lsp/SnykLanguageClientTest.kt
If $/snyk.hasAuthenticated transmits an API URL, this is saved in the settings.
> feat: automated-region-configuration (IDE-732)

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
- src/main/kotlin/io/snyk/plugin/analytics/AnalyticsScanListener.kt
- src/main/kotlin/io/snyk/plugin/analytics/AnalyticsSender.kt
- src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
- src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/analytics/AbstractAnalyticsEvent.kt
- src/main/kotlin/snyk/common/lsp/analytics/AnalyticsEvent.kt
- src/main/kotlin/snyk/common/lsp/analytics/ScanDoneEvent.kt
- src/test/kotlin/io/snyk/plugin/analytics/AnalyticsScanListenerTest.kt
- src/test/kotlin/snyk/common/lsp/LanguageServerWrapperTest.kt
This PR adds code to send analytics to track plugin installation. It could later be extended to send more events.
Depends on CLI preview release with protocol version 17
> feat: add plugin installed event [IDE-736]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
This sends the current configuration, including folder & project specific configs to language server before adding a project/folder to the configuration. That way, this config is considered in scans.
> fix: send config before adding a workspace folder [IDE-668]

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
- src/main/kotlin/io/snyk/plugin/services/CliAdapter.kt
- src/main/kotlin/io/snyk/plugin/ui/jcef/IgnoreInFileHandler.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
- src/test/kotlin/io/snyk/plugin/ui/jcef/IgnoreInFileHandlerTest.kt
This provides the logic to ignore an IaC finding for a specific file in the IntelliJ plugin, the ignore button is implicitly hidden and set to show in IntelliJ only.
The **HTML** panel that comes from the **Language Server** receives dynamic attributes with injected values such as the `path` and `Issue.ID`, these are extracted in a custom JS script and called through a callback when clicking **ignore button** , this triggers the `IgnoreHandler` .
In the `IgnoreHandler` the `IgnoreService` is called which calls calls the **CLI** through the **LS Wrapper** to execute the `snyk ignore` command on the specified params.
This path and issue id comes injected in the HTML template which comes from Snyk LS.
_Visuals that may help the reviewer. Please add screenshots for any UI change. GIFs are …
> fix: add iac ignore button [IDE-683]

- src/main/kotlin/io/snyk/plugin/ui/jcef/ThemeBasedStylingGenerator.kt
Replace the css variable needed for the new data-flow changes for HTML templates in LS. 
Related: https://github.com/snyk/snyk-ls/pull/733
> chore: replace css variable

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
Root Node base branch text was only initialized never updated, this PR updates it whenever the other RootTreeNodes update.
Note: The state is and was already saved as intended in the folder config.
> fix: update root node branch name on changing base branch [IDE-841]

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- Updates the `until` build property to unlimited, supporting by default new plugins.
- Fixes a bug with workspaceFolder config on shutdown/initialize
> chore: update IntelliJ plugin to support 2025.1, fix workspaceFolder config

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/BranchChooserComboboxDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/ReferenceChooserComboboxDialog.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
- src/test/kotlin/io/snyk/plugin/ui/BranchChooserComboBoxDialogTest.kt
- src/test/kotlin/io/snyk/plugin/ui/ReferenceChooserDialogTest.kt
This code change introduces the ability to specify a reference folder for Snyk scans, in addition to the existing base branch option. This is particularly useful for projects that are not under Git version control.
Here's a breakdown of the changes:
* **`FolderConfig`**:  A new field `referenceFolderPath` has been added to store the path of the reference folder.  Additionally, `scanCommandConfig` has been added to support running commands before and after a scan, optionally only on the reference folder.
* **`SnykToolWindowPanel.kt`**:
* `getRootNodeText()` now displays the reference folder information if it's set, otherwise it falls back to the base branch.
* The UI now updates to reflect the chosen reference folder. Error handling has been slightly improved.
* …
> feat: add reference folder to branch chooser

- src/main/kotlin/io/snyk/plugin/events/SnykScanListenerLS.kt
- src/main/kotlin/io/snyk/plugin/events/SnykShowIssueDetailListener.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindow.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/snyk/common/SnykCachedResults.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
Depending on the LSP method used, LS sends the either the long or the short product name ("Snyk Code" vs "code", for example). This was hard to track, and we had a few bugs where events were getting lost because we were comparing against the wrong strings.
This fix generalises the processing to handle either form, ensuring that all LS callbacks are handled.
> fix: update cache on receive diags

- CHANGELOG.md
- build.gradle.kts
- src/main/kotlin/snyk/errorHandler/SnykErrorReportSubmitter.kt
We had to remove usage of `AbstractMessage`, as Jetbrains marked it as internal API with 2025.1. This prevents plugin publishing on the marketplace. 
> chore: remove reporting of attachments to sentry [IDE-1046]

- CHANGELOG.md
- src/main/resources/META-INF/plugin.xml
Removing `com.intellij.modules.lang` to support Jetbrains Gateway. This should not be a problem, as we don't use the language features. Instead language server determines ranges and parses documents.
Removing the `com.intellij.modules.lang` dependency from an IntelliJ project can have significant impacts:
1. Loss of core language support: The `com.intellij.modules.lang` module provides essential language-related functionality for IntelliJ-based IDEs[9]. Removing this dependency may result in the loss of basic language features and APIs.
2. Reduced plugin compatibility: Many plugins rely on the language module for their functionality. Removing this dependency could make your plugin incompatible with other plugins or limit its capabilities[9].
3. Potential build and runtime errors: Your …
> chore: remove `com.intellij.modules.lang` dependency

- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/Types.kt
Previously, folderConfig did not implement comparable, even though we call `sorted` function on the list of configs. This leads to a ClassCastException
> fix: implement comparable on folderconfig

- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
In IDEs, you can configure a custom endpoint in order to target a custom region (e.g EU). The current description for this option is "Sets API endpoint to use for Snyk requests. Useful for custom Snyk setups. E.g. https://api.eu.snyk.io/.". With the recent platform changes, on OAuth using SSO, we automatically redirect to the right instance and that field does not need to be configured anymore.
Update
`If you're using SSO (OAuth2), API endpoint configuration is automatic. Otherwise, for public regional instances, see the docs. For private instances, contact your team or account manager.`
> fix: Update endpoint description [IDE-1056]

- src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
They are too unstable on CI unfortunately.
E.g. https://github.com/snyk/snyk-intellij-plugin/actions/runs/14597741442/job/40947912517
and https://github.com/snyk/snyk-intellij-plugin/actions/runs/14665426298/job/41158970310?pr=692
- Tests removed ;)
- N/A
- N/A
> chore: disable SnykToolWindowPanelIntegTest tests [IDE-611]

- src/main/kotlin/snyk/common/editor/DocumentChanger.kt
The previous code was based on bad logic for creating `WorkspaceEdit`s in the LS.
This LS bug has been fixed, but it isn't compatible with our code which expected the incorrect `WorkspaceEdit`s.
This has been fixed by applying the edits from the end of the file to the start of the file.
Unfortunately there is one case where this fix doesn't work, which is when applying a fix to the end of the file, if the file doesn't end with a LF character.
- No tests added, because I just want a fix in quickly before release, I will add some later.
- No, since we never released with applying WorkspaceEdits being broken.
- N/A
> fix: TextEdits applying to the wrong lines

- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
- src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
This Pull Request introduces functional, readability, and performance improvements across the codebase. Key updates include adjustments to optimize UI thread performance, the addition of helper methods for annotation refreshes, code formatting improvements, and changes enhancing maintainability.
- Updates the changelog to include a performance optimization for avoiding UI freezes in large projects.
- Refactors Utils.kt by improving null checks, enhancing readability, and adding functions to handle file annotations more efficiently.
- Optimizes the logic for refreshing open file annotations, including improvements for better performance based on file count.
- Refines the UI behavior in SnykToolWindowPanel.kt, simplifying redundant method calls while maintaining functionality.
- Enhances …
> fix: reduce usage of EDT in tree view and rendering updates, optimize data access paths

- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
Due to LS not putting `${ideScript}` in `<script>` tags in the IaC HTML, the JS was being displayed as text.
But `${ideScript}` is in `<script>` tags in the Code HTML, leading to an issue.
Luckily we can skip the issue, as the JS code injected is all stale now anyway.
Proof it is stale is below. Here are the only places they were being called (which have all been deleted):
- [`showAIFixes`](https://github.com/snyk/snyk-intellij-plugin/commit/f2ab96aa81f66c099187dd0f33aca2bf8fc21346#diff-2fe5cac6c04cc0d617b140ead2162807fcb566f072da5fc652a586a23c103972L188)
- [`showGenerateAIFixError`](https://github.com/snyk/snyk-intellij-plugin/commit/f2ab96aa81f66c099187dd0f33aca2bf8fc21346#diff-2fe5cac6c04cc0d617b140ead2162807fcb566f072da5fc652a586a23c103972L185)
- …
> fix: remove stale JS which was displayed in HTML [IDE-1204]

- src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/PanelHTMLUtils.kt
By using a space for replacements the attacker cannot use a bypass of using "${nonce${resolvesToEmpty}}".
> fix: prevent "${nonce}" check bypass [IDE-1050]

- .windsurfrules
- CHANGELOG.md
- src/main/kotlin/io/snyk/plugin/Utils.kt
- src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
- src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
- src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
- src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
- src/main/kotlin/snyk/common/lsp/settings/FolderConfigSettings.kt
- src/main/kotlin/snyk/trust/TrustedProjects.kt
- src/main/resources/html/ScanSummaryInit.html
- src/test/kotlin/io/snyk/plugin/UtilsKtTest.kt
- src/test/kotlin/io/snyk/plugin/ui/ReferenceChooserDialogTest.kt
- src/test/kotlin/snyk/common/lsp/settings/FolderConfigSettingsTest.kt
This PR improves URI and file path handling within the Snyk IntelliJ Plugin, with a primary focus on ensuring consistent normalization and absolutization of folder paths, particularly in `FolderConfigSettings`. These changes enhance reliability and prevent issues related to inconsistent path representations across different operating systems and user inputs.
**Key Changes and Fixes:**
*   **Consistent Path Normalization in `FolderConfigSettings`:**
*   Modified `FolderConfigSettings` to ensure that the `folderPath` property of stored `FolderConfig` objects is always the fully normalized and absolute path. This resolves inconsistencies where the stored path might not have matched the normalized key used in the internal map.
*   `addFolderConfig` now stores a copy of the input …
> fix: URI handling for URIs with special/blank characters [IDE-1203][IDE-1235]

- .github/workflows/release.yml
- build.gradle.kts
- gradle.properties
> chore: try to get test step running in release

- src/main/kotlin/io/snyk/plugin/ui/ReferenceChooserComboboxDialog.kt
Now correctly listens to changes in the reference folder text fields and submits changes in folderconfigs to Snyk Language Server.
> fix: added listener for reference folder changes
