src/main/scala/io/snyk/plugin/client/SnykConfig.scala

adding plugin origin parameter in url for analytics purposes.

feat: add plugin parameter auth url

---

src/main/scala/io/snyk/plugin/depsource/MavenProjectsObservable.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
src/test/resources/sample-response-for-maven-observable-test.json
src/test/scala/io/snyk/plugin/MavenProjectsObservableTest.scala

Data was updated with delay or not updated at all. To fix it MavenProjectsTree.Listener was replaced with MavenProjectsManager.Listener.

Fix: update maven vulnerabilities issue. 

---

src/main/scala/io/snyk/plugin/client/ApiClient.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
src/test/scala/io/snyk/plugin/AbstractMavenTestCase.scala
src/test/scala/io/snyk/plugin/MavenProjectsObservableTest.scala
src/test/scala/io/snyk/plugin/SnykBasicPluginTest.scala
src/test/scala/io/snyk/plugin/SnykCLIApiClientTest.scala

This version replaces Maven API call using JSON payload of all dependencies with Snyk CLI call.

Feat: replace maven api call with snyk cli call

---

build.gradle
src/main/resources/META-INF/plugin.xml
src/main/scala/io/snyk/plugin/datamodel/MavenCoords.scala
src/main/scala/io/snyk/plugin/datamodel/SnykMavenArtifact.scala
src/main/scala/io/snyk/plugin/depsource/BuildToolProject.scala
src/main/scala/io/snyk/plugin/depsource/DepTreeProvider.scala
src/main/scala/io/snyk/plugin/depsource/GradleProjectsObservable.scala
src/main/scala/io/snyk/plugin/depsource/ProjectType.scala
src/main/scala/io/snyk/plugin/ui/ExternalPopupHandler.scala
src/main/scala/io/snyk/plugin/ui/NotificationService.scala
src/main/scala/io/snyk/plugin/ui/SnykToolWindow.scala
src/main/scala/io/snyk/plugin/ui/state/Navigator.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
src/test/resources/sample-gradle.build
src/test/scala/io/snyk/plugin/AbstractGradleTestCase.scala
src/test/scala/io/snyk/plugin/AbstractMavenTestCase.scala
src/test/scala/io/snyk/plugin/AbstractTestCase.scala
src/test/scala/io/snyk/plugin/SnykGradleProjectPluginTest.scala
src/test/scala/io/snyk/plugin/SnykMavenProjectPluginTest.scala

Added basic Gradle support for Snyk CLI plugin.

Feat: add Gradle support

---

src/main/resources/WEB-INF/html/error.hbs
src/main/scala/io/snyk/plugin/datamodel/Vulnerability.scala
src/main/scala/io/snyk/plugin/embeddedserver/ServerResponses.scala
src/main/scala/io/snyk/plugin/ui/annotators/SnykMavenRedUnderlineAnnotator.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala

Fixed display of long text errors.
Added message how can user can fix the error in the case of Maven projects.

Fix: add display cli error message

---

src/main/scala/io/snyk/plugin/client/ApiClient.scala
src/main/scala/io/snyk/plugin/embeddedserver/ServerResponses.scala
src/main/scala/io/snyk/plugin/ui/annotators/SnykMavenRedUnderlineAnnotator.scala

Fix display error message from CLI in case of multi-module projects. In the case of a multi-module project, CLI returns plain text +  JSON.

Fix: fix display error message for multi module project.

---

src/main/scala/io/snyk/plugin/depsource/DepTreeProvider.scala

Fixed UI error: java.lang.AssertionError: Already disposed: Project (Disposed) [project name].

Fix: fixed java.lang.AssertionError Already disposed Project.

---

src/main/scala/io/snyk/plugin/depsource/MavenProjectsObservable.scala
src/test/scala/io/snyk/plugin/SnykGradleMultiModuleTest.scala
src/test/scala/io/snyk/plugin/SnykGradleProjectPluginTest.scala
src/test/scala/io/snyk/plugin/SnykMavenMultiModuleTest.scala
src/test/scala/io/snyk/plugin/SnykMavenProjectPluginTest.scala
src/test/scala/io/snyk/plugin/SnykVulnResponseTest.scala

Fixed unit tests.
Fixed issue with auto scan on file changes event.

Fix: fix unit tests

---

build.gradle

Updated plugin version from "0.1.2" to "0.2.0".

Feat: updated plugin version.

---

build.gradle
src/main/resources/META-INF/plugin.xml
src/main/scala/io/snyk/plugin/ui/annotators/SnykGradleRedUnderlineAnnotator.scala
src/main/scala/io/snyk/plugin/ui/annotators/SnykMavenRedUnderlineAnnotator.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
src/test/resources/properties-response-for-annotator-test.json
src/test/resources/sample-response-for-annotator-from-dependencies-test.json
src/test/resources/sample-response-for-gradle-annotator-different-config-types.json
src/test/resources/sample-response-for-gradle-annotator-test.json
src/test/scala/io/snyk/plugin/SnykGradleRedUnderlineAnnotatorTest.scala
src/test/scala/io/snyk/plugin/SnykMavenRedUnderlineAnnotatorTest.scala

Added Gradle annotator.
Fixed display of red underlines for Maven.

Feat: add gradle annotator

---

build.gradle
src/main/scala/io/snyk/plugin/Implicits.scala
src/main/scala/io/snyk/plugin/SnykPluginProjectComponent.scala
src/main/scala/io/snyk/plugin/client/CliClient.scala
src/main/scala/io/snyk/plugin/client/ConsoleCommandRunner.scala
src/main/scala/io/snyk/plugin/client/SnykClientSerialisation.scala
src/main/scala/io/snyk/plugin/datamodel/ProjectDependency.scala
src/main/scala/io/snyk/plugin/depsource/BuildToolProject.scala
src/main/scala/io/snyk/plugin/depsource/DepTreeProvider.scala
src/main/scala/io/snyk/plugin/embeddedserver/MiniServer.scala
src/main/scala/io/snyk/plugin/ui/annotators/SnykGradleRedUnderlineAnnotator.scala
src/main/scala/io/snyk/plugin/ui/annotators/SnykMavenRedUnderlineAnnotator.scala
src/main/scala/io/snyk/plugin/ui/state/PerProjectState.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
src/test/scala/io/snyk/plugin/MavenProjectsObservableTest.scala
src/test/scala/io/snyk/plugin/MiniServerTest.scala
src/test/scala/io/snyk/plugin/SegmentApiTest.scala
src/test/scala/io/snyk/plugin/SnykCliClientTest.scala
src/test/scala/io/snyk/plugin/SnykGradleMultiModuleTest.scala
src/test/scala/io/snyk/plugin/SnykGradleProjectPluginTest.scala
src/test/scala/io/snyk/plugin/SnykGradleRedUnderlineAnnotatorTest.scala
src/test/scala/io/snyk/plugin/SnykMavenMultiModuleTest.scala
src/test/scala/io/snyk/plugin/SnykMavenProjectPluginTest.scala
src/test/scala/io/snyk/plugin/SnykMavenRedUnderlineAnnotatorTest.scala

Added Maven install goal run before CLI call for Maven multi-module projects.
Added unit tests.
Refactoring of CliClient.

Feat: add maven install for multi module maven projects

---

src/main/scala/io/snyk/plugin/depsource/DepTreeProvider.scala

For Maven multi-module projects project title in the Snyk toolbar was displayed as one of the sub-projects, not the main project. Current changes fix this problem.

Fix: project title in Snyk toolbar for Maven multi module projects.

---

README.md
src/main/resources/META-INF/plugin.xml

This PR updates the plugin information in JetBrains marketplace:
- sync info from Google doc
- show change notes in reversed order (latest first)

docs: update plugin information

---

src/main/scala/io/snyk/plugin/datamodel/Vulnerability.scala
src/test/resources/sample-response-for-license-with-empty-template-url.json
src/test/scala/io/snyk/plugin/LicenseVulnerabilityTest.scala

Fix issue with deserialization of unknown license with empty license URL. 
Added test.

Fix: fix issue with deserialization of unknown license with empty license url

---

.travis.yml

This PR fix Travis build condition for stable builds.

chore: fix build condition for stable builds

---

.travis.yml
src/main/resources/META-INF/plugin.xml
src/main/scala/io/snyk/plugin/client/CliClient.scala
src/main/scala/io/snyk/plugin/ui/settings/SettingsDialog.scala
src/main/scala/io/snyk/plugin/ui/settings/SnykConfigurable.scala
src/main/scala/io/snyk/plugin/ui/settings/SnykIntelliJSettings.scala
src/main/scala/io/snyk/plugin/ui/settings/SnykPersistentStateComponent.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
src/test/scala/io/snyk/plugin/SnykCliClientTest.scala
src/test/scala/io/snyk/plugin/SnykGradleMultiModuleTest.scala
src/test/scala/io/snyk/plugin/SnykMavenMultiModuleTest.scala

Added settings dialog.
Tests fixed.

Feat: add settings

---

src/main/scala/io/snyk/plugin/SnykPluginProjectComponent.scala

Fix "Getting Started With CLI" URL format.

Fix: fix Getting Started With CLI URL format.

---

src/main/scala/io/snyk/plugin/SnykPluginProjectComponent.scala
src/main/scala/io/snyk/plugin/client/CliClient.scala
src/main/scala/io/snyk/plugin/client/CliDownloader.scala
src/main/scala/io/snyk/plugin/client/Platform.scala
src/main/scala/io/snyk/plugin/ui/state/SnykPluginState.scala
src/test/scala/io/snyk/plugin/CliDownloaderTestCase.scala
src/test/scala/io/snyk/plugin/PlatformTest.scala
src/test/scala/io/snyk/plugin/SnykCliClientTest.scala

Added automatic loading of Snyk CLI in the background mode.
Added unit tests.

Feat: cli auto install

---

gradle.properties

Prepare to release version `0.2.3`.

chore: bump patch version

---

gradle.properties
src/main/scala/io/snyk/plugin/client/CliClient.scala
src/main/scala/io/snyk/plugin/ui/settings/SettingsDialog.scala
src/main/scala/io/snyk/plugin/ui/settings/SnykIntelliJSettingsState.scala
src/main/scala/io/snyk/plugin/ui/settings/SnykPersistentStateComponent.scala
src/test/scala/io/snyk/plugin/SnykCliClientTest.scala

Added additional parameters in settings for Snyk CLI.

Feat: add additional parameters settings for cli

---

build.gradle
gradle.properties
src/main/scala/io/snyk/plugin/client/CliClient.scala
src/main/scala/io/snyk/plugin/client/ConsoleCommandRunner.scala
src/test/resources/sample-multi-module-web-pom.xml
src/test/resources/sample-pom-with-unavailable-dependency.xml
src/test/scala/io/snyk/plugin/AbstractTestCase.scala
src/test/scala/io/snyk/plugin/ConsoleCommandRunnerTest.scala
src/test/scala/io/snyk/plugin/SnykCliClientTest.scala
src/test/scala/io/snyk/plugin/SnykGradleMultiModuleTest.scala
src/test/scala/io/snyk/plugin/SnykGradleProjectPluginTest.scala
src/test/scala/io/snyk/plugin/SnykMavenMultiModuleTest.scala

Fixed issue with  CLI infinite execution if "mvn install" failed.
Added unit tests.

Fix: cli infinite execution if mvn install failed issue

---

src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt

This PR adds `SNYK_INTEGRATION_NAME` and `SNYK_INTEGRATION_VERSION` envvar for the plugin.

feat: set integration name and version values

---

src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt

Replaced token text field with a password field.

Fix: replaced text field with password field for token.

---

src/main/kotlin/icons/SnykIcons.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindow.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
src/main/resources/META-INF/plugin.xml

Moved Icons class to icons package and rename to SnykIcons to use in plugin configuration files.

chore: improved Icons class to use in plugin configuration files.

---

src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
src/test/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt

Added additional flags with a version and JetBrains product name for CLI.

Feat: add JB type integration flag

---

gradle.properties
src/main/kotlin/io/snyk/plugin/cli/Vulnerability.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/FileTreeNode.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityDescriptionPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeNode.kt
src/test/resources/group-vulnerabilities-goof-test.json

See commit messages for details.
Mostly refactoring CLI results UI building process and redesign UI by Andy's design and web results presentation as the baseline.

Feat: improve cli results description panel

---

.github/workflows/release.yml
CHANGELOG.md
build.gradle.kts
src/main/java/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.java
src/main/kotlin/io/snyk/plugin/analytics/EventProperties.kt
src/main/kotlin/io/snyk/plugin/analytics/EventPropertiesProvider.kt
src/main/kotlin/io/snyk/plugin/analytics/Segment.kt
src/main/kotlin/io/snyk/plugin/analytics/internal/SnykApiClient.kt
src/main/kotlin/io/snyk/plugin/analytics/internal/TokenInterceptor.kt
src/main/kotlin/io/snyk/plugin/analytics/internal/UserService.kt
src/main/kotlin/io/snyk/plugin/services/SnykAnalyticsService.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/OnboardPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/resources/application.properties
src/test/kotlin/io/snyk/plugin/analytics/EventPropertiesProviderTest.kt
src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt

This PR adds integration with Segment analytics.

feat: analytics integration

---

.github/CODEOWNERS

This PR changes the codeowner for the project.

chore: codeowners -> road-runner

---

gradle.properties

This PR prepares a release v2.1.0.

chore: prepare release v2.1.0

---

README.md

Update the plugin description with new Snyk Code functionality.

docs: update plugin description

---

CHANGELOG.md
build.gradle.kts
gradle.properties
src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt

will fix https://snyksec.atlassian.net/browse/ROADRUNNER-111

fix: `missing file parameter` exception [ROADRUNNER-111]

---

src/main/kotlin/io/snyk/plugin/cli/CliGroupedResult.kt
src/main/kotlin/io/snyk/plugin/cli/CliVulnerabilitiesForFile.kt
src/main/kotlin/io/snyk/plugin/cli/Vulnerability.kt
src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeResults.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityDescriptionPanel.kt
src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt
src/test/resources/group-vulnerabilities-goof-test.json

Default value for all fields gotten from JSON, with post check for initialization by actual values on get().
PS should fix #107

fix: json with missed fields parsing [ROAD-12]

---

CHANGELOG.md
gradle.properties

This PR prepares `2.1.4` release to marketplace.

chore: prepare release 2.1.4

---

src/main/kotlin/io/snyk/plugin/analytics/internal/CliConfigService.kt
src/main/kotlin/io/snyk/plugin/analytics/internal/SnykApiClient.kt

This PR adds an endpoint to query SAST settings for Snyk Code.

feat: add endpoint for SAST configuration [ROAD-7]

---

CHANGELOG.md
gradle.properties
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt

fix: Exception when Settings panel invoked

---

CHANGELOG.md
gradle.properties

This PR bumps version to 2.1.7 and updates changelog.

chore: prepare release 2.1.7

---

src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliAuthenticationService.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityDescriptionPanel.kt

- display auth link for possibility of manual open/copy in browser [ROAD-125]
- also error notification in case of auth failure (like 30 sec CLI timeout)
[ROAD-125]: https://snyksec.atlassian.net/browse/ROAD-125

feat: display auth link for possibility of manual open/copy in browser [ROAD-125]

---

src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
src/main/kotlin/io/snyk/plugin/events/SnykCliDownloadListener.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliAuthenticationService.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliDownloaderService.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/test/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt
src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt

Also include blocking Auth execution possibility while CLI is still downloading.
More info at https://snyksec.atlassian.net/browse/ROAD-177
PS not to be included into (i.e. blocking) upcoming 2.1.8 release

fix: ProcessNotCreatedException if try to run CLI command while CLI is still downloading [ROAD-177]

---

src/test/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt

Previous version of test relay on relatively long CLI downloading process (with 100Mb/s channel it takes ~10 sec). 
But while performing tests on GitHub CI, the CLI is downloading (from GitHub) very fast and that should be considered.

test: fix `CLI command execution while CLI is downloading` test

---

build.gradle.kts
src/main/kotlin/snyk/advisor/AdvisorService.kt
src/main/kotlin/snyk/advisor/api/AdvisorApiClient.kt
src/main/kotlin/snyk/advisor/api/ScoreService.kt
src/main/kotlin/snyk/net/HttpClient.kt
src/main/kotlin/snyk/net/HttpLoggingInterceptor.kt
src/test/kotlin/snyk/advisor/api/AdvisorApiClientTest.kt
src/test/resources/text-fixtures/api-responses/advisor/scores-npm-packages_empty-payload_404.json
src/test/resources/text-fixtures/api-responses/advisor/scores-npm-packages_multiple-packages-payload_200.json
src/test/resources/text-fixtures/api-responses/advisor/scores-npm-packages_non-existing-package_200.json
src/test/resources/text-fixtures/api-responses/advisor/scores-python-packages_empty-payload_404.json
src/test/resources/text-fixtures/api-responses/advisor/scores-python-packages_multiple-packages-payload_200.json
src/test/resources/text-fixtures/api-responses/advisor/scores-python-packages_non-existing-package_200.json

This PR adds the Retrofit client for Advisor API.
Additionally OKHttpClient is refactored to be able to use in our other API clients.

feat: add Advisor API client [ROAD-150]

---

.github/detekt/detekt-baseline.xml
.github/detekt/detekt-config.yml
.github/workflows/build.yml
.github/workflows/detekt.yml
build.gradle.kts

This PR adds detekt (https://detekt.github.io/detekt/) integration via Gradle task and PR check.
PR check is **not required** for now.

feat: add detekt plugin [ROAD-43]

---

src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/snyk/advisor/SnykAdvisorEditorLinePainter.kt

!!! Should/Will be merged after (based on) #135 
- Advisor on/off option on Settings/Welcome screens; 
- Help hints for other checkboxesж
- Redesign for Settings screen

Advisor on/off settings [ROAD-200]

---

CHANGELOG.md
gradle.properties

This PR prepares a new release `v2.2.1`.

chore: prepare release 2.2.1

---

build.gradle.kts

This PR fixes an issue with failing `runIde` Gradle command.

fix: runIde task [ROAD-229]

---

.github/workflows/release.yml
build.gradle.kts
src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
src/main/kotlin/snyk/amplitude/AmplitudeExperimentService.kt
src/main/resources/application.properties

This PR adds Amplitude experiment to show scanning reminder.

feat: add scanning reminder experiment [ROAD-165]

---

src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliDownloaderService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

fix: disable Run scan action if Cli is downloading;
fix: on scan invocation download Cli first if needed.

fix: Cli invocation issues [ROAD-250]

---

README.md

This PR adds information about Advisor into README.md.

doc: add information about Advisor into readme

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowFactory.kt
src/main/kotlin/snyk/WelcomeNotifyActivity.kt
src/main/resources/META-INF/plugin.xml

This PR shows welcome notification with link to Snyk tool window, after first plugin installation.

feat: show welcome notification after first plugin installation [ROAD-176]

---

src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
src/integTest/kotlin/io/snyk/plugin/services/SnykCliDownloaderServiceTest.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliAuthenticationService.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliDownloaderService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt

fix: NullPointerException when no release info available [ROAD-187]

---

.github/workflows/build.yml
build.gradle.kts
gradle.properties

Add runPluginVerifier Gradle task and add Github action for it.

[ROAD-243] Feat: add run plugin verifier task.

---

src/main/kotlin/io/snyk/plugin/ui/toolwindow/OnboardPanel.kt

fix for https://snyk.slack.com/archives/C01F0L6C8JK/p1630837468099800

fix: remove logo from Product selection panel [ROAD-290]

---

CHANGELOG.md
gradle.properties

This PR prepares release ~v2.3.2~ v2.3.0

chore: bump version to 2.3.0 and update release notes

---

src/main/kotlin/snyk/advisor/AdvisorEditorFactoryListener.kt
src/main/kotlin/snyk/advisor/PackageNameProvider.kt

fix: exception when Advisor analyse in-memory (no VirtualFile) file [ROAD-280]

---

src/integTest/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateServiceTest.kt
src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykTreeScanTypeFilterAction.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
src/main/kotlin/snyk/container/BaseImageRemediationExtractor.kt
src/test/kotlin/snyk/container/BaseImageRemediationExtractorTest.kt

- at Welcome(prod selection) screen
- in the plugin's Settings
- in the Tree filters

feat: IaC and Container scan enablement options:

---

src/main/resources/META-INF/plugin.xml

due to some hard to catch issues with dynamic services unload/load

fix: request Idea restart after plugin update [ROAD-390]

---

build.gradle.kts
gradle.properties
src/integTest/kotlin/snyk/iac/annotator/IacBaseAnnotatorCase.kt
src/integTest/kotlin/snyk/iac/annotator/IacHclAnnotatorTest.kt
src/integTest/kotlin/snyk/iac/annotator/IacJsonAnnotatorTest.kt
src/integTest/kotlin/snyk/iac/annotator/IacYamlAnnotatorTest.kt
src/integTest/resources/test-fixtures/iac/annotator/cloudformation-deployment.yaml
src/integTest/resources/test-fixtures/iac/annotator/kubernetes-deployment.yaml
src/integTest/resources/test-fixtures/iac/annotator/terraform-main.tf
src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/iac/IacIssuesForFile.kt
src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt
src/main/kotlin/snyk/iac/annotator/IacHclAnnotator.kt
src/main/kotlin/snyk/iac/annotator/IacJsonAnnotator.kt
src/main/kotlin/snyk/iac/annotator/IacYamlAnnotator.kt
src/main/resources/META-INF/optional/io.snyk.snyk-intellij-plugin-withHCL.xml
src/main/resources/META-INF/optional/io.snyk.snyk-intellij-plugin-withJSON.xml
src/main/resources/META-INF/optional/io.snyk.snyk-intellij-plugin-withYAML.xml
src/main/resources/META-INF/plugin.xml

This PR add a feature to propagate IaC issues to IntelliJ problems (view).
It's done via external annotator extension point: https://plugins.jetbrains.com/docs/intellij/syntax-highlighting-and-error-highlighting.html#external-tool

feat: propagate IaC issue to problems tool window [ROAD-378]

---

src/integTest/kotlin/UIComponentFinder.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykErrorPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

fix: IaC errors display in description panel [ROAD-486]

---

src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
src/main/kotlin/snyk/amplitude/AmplitudeExperimentService.kt

don't ask Amplitude for this experiment anymore, only use setting if it was shown. If not, show it, update the setting and don't show it again.

chore: 🧹 enabled experiment code for scanning reminder for all [ROAD-503]

---

src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/snyk/iac/IacSuggestionDescriptionPanel.kt

fix: 🐛️ wrap description, impact and path lines in iac issues [ROAD-559]

---

src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/settings/ScanTypesPanelTest.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt

To enable use `snyk.preview.container.enabled` Idea Registry key:

feat: Container on product selection and settings screens [ROAD-449]

---

src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/integTest/kotlin/snyk/advisor/PackageNameProviderTest.kt
src/integTest/kotlin/snyk/iac/annotator/IacBaseAnnotatorCase.kt
src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

- extracted SnykScanListener closure as variable to be able to directly call it
- added a constant that identifies the error message that should be an info
- added an if to check for that constant
- wrote an integration test verifying that this error message is displayed as info, others as error

Oss plugin displays error if no supported package manager is found [ROAD-463]

---

src/main/kotlin/io/snyk/plugin/ui/toolwindow/LabelProvider.kt
src/main/kotlin/snyk/iac/IacSuggestionDescriptionPanel.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/LabelProviderTest.kt
src/test/kotlin/snyk/iac/IacSuggestionDescriptionPanelTest.kt

feat: ✨ surface infrastructure as code reference links [ROAD-573]

---

src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/main/kotlin/icons/SnykIcons.kt
src/main/kotlin/io/snyk/plugin/Severity.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/cli/CliResult.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
src/main/kotlin/snyk/container/ContainerService.kt
src/main/kotlin/snyk/container/ui/BaseImageRemediationDetailPanel.kt
src/main/kotlin/snyk/container/ui/ContainerImageTreeNode.kt
src/main/resources/icons/container_image_24.svg

container image node description panel [ROAD-452]

---

CHANGELOG.md
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

- removed balloons for oss and iac

chore: 💄 don't flood user with notifications when no OSS / IaC files are found [ROAD-477]

---

src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/LabelProvider.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityDescriptionPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
src/main/kotlin/snyk/container/ContainerIssues.kt
src/main/kotlin/snyk/container/ui/BaseImageRemediationDetailPanel.kt
src/main/kotlin/snyk/container/ui/ContainerIssueDetailPanel.kt
src/main/kotlin/snyk/container/ui/ContainerIssueTreeNode.kt
src/main/kotlin/snyk/iac/IacSuggestionDescriptionPanel.kt
src/main/kotlin/snyk/oss/Vulnerability.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/LabelProviderTest.kt
src/test/kotlin/snyk/iac/IacSuggestionDescriptionPanelTest.kt

Also refactoring of description panels (OSS, IaC) UI to extract some common parts.

Container issue node and description panel [ROAD-451]

---

.github/workflows/release.yml

Enable automatic plugin publishing in release workflow.

chore: enable plugin publishing in release workflow

---

src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
src/integTest/kotlin/io/snyk/plugin/services/CliAdapterTest.kt
src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
src/main/kotlin/io/snyk/plugin/services/CliAdapter.kt

https://user-images.githubusercontent.com/20150761/151576196-23e6f835-1833-42d4-adcb-80b658aa999b.mov

feat: ✨Support Single Tenant in IntelliJ (OSS/IAC/CONTAINER) [ROAD-623]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

fix: [InvocationTargetException ](https://sentry.io/organizations/snyk/issues/2980659540/?project=5956531&referrer=slack)on project-less authentication;
fix: memory leak in Authentication panel

fix some annoying exceptions

---

CHANGELOG.md
gradle.properties
src/main/kotlin/snyk/common/IgnoreService.kt
src/main/kotlin/snyk/iac/IgnoreButtonActionListener.kt
src/test/kotlin/snyk/common/IgnoreServiceTest.kt
src/test/kotlin/snyk/iac/IgnoreButtonActionListenerTest.kt

dependent on: https://github.com/snyk/snyk/pull/2629

feat: ✨ ignore only instance of issue on ignore button click in iac [ROAD-628]

---

README.md

This PR includes IaC and Container into marketplace description.

doc: update readme with iac and container description for marketplace [ROAD-653]

---

src/integTest/kotlin/io/snyk/SnykBulkFileListenerTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/integTest/kotlin/snyk/container/ContainerServiceIntegTest.kt
src/integTest/kotlin/snyk/container/KubernetesImageCacheIntegTest.kt
src/integTest/kotlin/snyk/container/annotator/ContainerYamlAnnotatorTest.kt
src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
src/main/kotlin/snyk/container/ContainerIssues.kt
src/main/kotlin/snyk/container/ContainerResult.kt
src/main/kotlin/snyk/container/KubernetesImageCache.kt
src/main/kotlin/snyk/container/KubernetesWorkloadImage.kt
src/main/kotlin/snyk/container/YAMLImageExtractor.kt
src/main/kotlin/snyk/container/annotator/ContainerYamlAnnotator.kt
src/main/kotlin/snyk/container/ui/BaseImageRemediationDetailPanel.kt
src/main/kotlin/snyk/iac/IacIssuesForFile.kt
src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt
src/test/kotlin/snyk/container/YAMLImageExtractorTest.kt

~~logic to be more carefully tested~~ done
~~tests to be added~~ done

feat: clean/update Container cached results [ROAD-646]

---

CHANGELOG.md
src/integTest/kotlin/io/snyk/SnykBulkFileListenerTest.kt
src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/settings/ScanTypesPanelTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/iac/IgnoreButtonActionListener.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt

feat: ✨ make Snyk Container and Snyk Infrastructure as Code available for everyone [ROAD-725]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt
src/main/kotlin/snyk/advisor/buildsystems/NpmSupport.kt
src/main/kotlin/snyk/advisor/buildsystems/PythonSupport.kt
src/main/kotlin/snyk/container/annotator/ContainerYamlAnnotator.kt
src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt

gonna fix IndexOutOfBoundsException observing in Sentry

fix: sanitize line number before document.getLineOffset()

---

CHANGELOG.md
src/integTest/kotlin/snyk/code/annotator/SnykCodeAnnotatorTest.kt
src/integTest/kotlin/snyk/container/KubernetesImageCacheIntegTest.kt
src/integTest/kotlin/snyk/container/TestYamls.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/code/annotator/SnykCodeAnnotator.kt
src/main/kotlin/snyk/common/AnnotatorCommon.kt
src/main/kotlin/snyk/container/YAMLImageExtractor.kt
src/main/kotlin/snyk/oss/annotator/OSSBaseAnnotator.kt
src/main/kotlin/snyk/oss/annotator/OSSNpmAnnotator.kt

chore: improve on Snyk Code Annotator [ROAD-668] [ROAD-737]

---

src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/net/CliConfigService.kt
src/main/kotlin/io/snyk/plugin/net/SnykApiClient.kt
src/main/kotlin/io/snyk/plugin/net/TokenInterceptor.kt
src/main/kotlin/io/snyk/plugin/services/SnykApiService.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt

This PR adds a new feature for Snyk Code => disable it if local code engine is enabled.
Configuration screen:
Tree:

feat: block LCE upload for Snyk Code [ROAD-687]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/LabelProvider.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/LabelProviderTest.kt

The problem - https://snyk.slack.com/archives/C01M63AMWD6/p1645605884256919.

fix: case sensitivity for vuln id in label provider crafted url

---

CHANGELOG.md
README.md
gradle.properties
src/main/resources/META-INF/plugin.xml

chore: rename plugin to `Snyk Security - Code, Open Source, Container, IaC Configurations` [ROAD-654]

---

CHANGELOG.md
src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/main/kotlin/io/snyk/plugin/cli/ConsoleCommandRunner.kt
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/IssueDescriptionPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/StatePanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityDescriptionPanel.kt
src/main/kotlin/snyk/container/ui/BaseImageRemediationDetailPanel.kt
src/main/kotlin/snyk/container/ui/ContainerIssueDetailPanel.kt
src/main/kotlin/snyk/iac/IacSuggestionDescriptionPanel.kt

Some edge cases are omitted, due to complexity of logic inside SnykToolWindow. Most real cases seems to be covered.

feat: added Container specific messages when Container root tree node is selected [ROAD-689]

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/io/snyk/plugin/snykcode/CodeRestApi.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/AnalysisData.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/RunUtils.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeParams.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeUtils.kt

~~use snyk-code-client 2.3.0, so it need to be published to the maven first~~ done

update java-client to 2.3.0 to make analysis retrieval more resilient and to send analysis context [ROAD-742][ROAD-730]

---

CHANGELOG.md
src/main/kotlin/snyk/oss/annotator/OSSNpmAnnotator.kt

Will fix `ClassNotFoundException: org.jetbrains.kotlin.psi.psiUtil`

fix: Usage of kotlin-plugin specific method removed

---

CHANGELOG.md
src/main/kotlin/snyk/common/AnnotatorCommon.kt

Disable force [auto-save in annotators](https://github.com/snyk/snyk-intellij-plugin/issues/324)

fix: Disable force auto-save in annotators [ROAD-773]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

will prevent https://sentry.io/organizations/snyk/issues/3142615100 kind of exception.

fix: Sanitize TextRange in file before accessing it

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykCleanScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykStopScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

will fix [IncorrectOperationException](https://sentry.io/organizations/snyk/issues/3023294926/?referrer=slack)

avoiding IncorrectOperationException by remove direct project service's requests.

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykCleanScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykStopScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/advisor/buildsystems/NpmSupport.kt

will fix [NoClassDefFoundError](https://sentry.io/organizations/snyk/issues/3160811471/?referrer=slack)

fix: avoid ClassNotFoundException due to not bundled Json support in some IDE.

---

src/integTest/kotlin/UIComponentFinder.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelIntegTest.kt
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/IssueDescriptionPanelBase.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityDescriptionPanel.kt
src/main/kotlin/snyk/container/ui/BaseImageRemediationDetailPanel.kt
src/main/kotlin/snyk/container/ui/ContainerIssueDetailPanel.kt
src/main/kotlin/snyk/iac/IacSuggestionDescriptionPanel.kt

~~!!!Could/should be reviewed after #348 only!!!~~ will substitute #348

Report False Positive button (empty yet) for Code results [ROAD-541]

---

CHANGELOG.md
build.gradle.kts

to support min and max file sizes better

update code-api to 2.3.1

---

src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/ReportFalsePositiveDialogIntegTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelIntegTest.kt
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/IssueDescriptionPanelBase.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/ReportFalsePositiveDialog.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityDescriptionPanel.kt
src/main/kotlin/snyk/container/ui/BaseImageRemediationDetailPanel.kt
src/main/kotlin/snyk/container/ui/ContainerIssueDetailPanel.kt
src/main/kotlin/snyk/iac/IacSuggestionDescriptionPanel.kt

feat: `Report False Positive` dialog added (with editor's placeholder yet) [ROAD-541]

---

CHANGELOG.md
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/settings/ScanTypesPanelTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeParams.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykTreeScanTypeFilterAction.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/snyk/common/CustomEndpoints.kt
src/test/kotlin/snyk/common/CustomEndpointsTest.kt

This PR handles Deeproxy URL configuration for single tenant instance.
All code related to work with custom endpoints is moved to `CustomEndpoints.kt` file.

feat: add helper for custom endpoint [ROAD-828]

---

src/main/kotlin/io/snyk/plugin/analytics/ItlyHelper.kt
src/test/kotlin/io/snyk/plugin/analytics/ItlyHelperTest.kt

Currently we can see container analysis issues being reported to analytics however cannot see container analysis being triggered. 
Now we can check if the container analysis is enabled and then we can reporting that. 

fix: capturing container analysis for analytics [ROAD-832]

---

src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/analytics/Iteratively.kt
src/main/kotlin/io/snyk/plugin/services/SnykAnalyticsService.kt
src/main/kotlin/io/snyk/plugin/services/SnykApiService.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliAuthenticationService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderErrorHandler.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/advisor/AdvisorScoreProvider.kt
src/main/kotlin/snyk/advisor/SnykAdvisorModel.kt
src/main/kotlin/snyk/common/intentionactions/AlwaysAvailableReplacementIntentionAction.kt
src/main/kotlin/snyk/container/annotator/BaseImageRemediationFix.kt

Will help to control/change way we do services invocation/instantiation
Also prepare code base to be buildable with 221

chore: centralize services invocation [ROAD-862]

---

src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/ReportFalsePositiveDialogIntegTest.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/ReportFalsePositiveDialog.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt

feat: read/write editors for `Report False Positive` dialog [ROAD-542]

---

src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelIntegTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/net/CliConfigService.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt

feat: Allow reporting false positive only with existing entitlement [ROAD-792]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt

will fix [Throwable](https://sentry.io/organizations/snyk/issues/3216148344/?referrer=slack)

fix: failed psiFile search for invalid virtualFile

---

CHANGELOG.md
src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/integTest/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/integTest/kotlin/snyk/container/ContainerBulkFileListenerTest.kt
src/integTest/kotlin/snyk/container/annotator/ContainerYamlAnnotatorTest.kt
src/integTest/kotlin/snyk/iac/IacBulkFileListenerTest.kt
src/integTest/kotlin/snyk/iac/annotator/IacBaseAnnotatorCase.kt
src/integTest/kotlin/snyk/iac/annotator/IacHclAnnotatorTest.kt
src/integTest/kotlin/snyk/iac/annotator/IacJsonAnnotatorTest.kt
src/integTest/kotlin/snyk/iac/annotator/IacYamlAnnotatorTest.kt
src/integTest/kotlin/snyk/oss/OssBulkFileListenerTest.kt
src/integTest/kotlin/snyk/oss/annotator/OSSGoModAnnotatorTest.kt
src/integTest/kotlin/snyk/oss/annotator/OSSGradleKtsAnnotatorTest.kt
src/integTest/kotlin/snyk/oss/annotator/OSSMavenAnnotatorTest.kt
src/integTest/kotlin/snyk/oss/annotator/OSSNpmAnnotatorTest.kt
src/main/kotlin/io/snyk/plugin/SnykBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/VulnerabilityTreeCellRenderer.kt
src/main/kotlin/snyk/common/SnykCachedResults.kt
src/main/kotlin/snyk/container/ContainerBulkFileListener.kt
src/main/kotlin/snyk/container/annotator/ContainerYamlAnnotator.kt
src/main/kotlin/snyk/iac/IacBulkFileListener.kt
src/main/kotlin/snyk/iac/annotator/IacBaseAnnotator.kt
src/main/kotlin/snyk/oss/OssBulkFileListener.kt
src/main/kotlin/snyk/oss/annotator/OSSBaseAnnotator.kt

fix: `InvocationTargetExceptions` by extracting caches to separate class [ROAD-813]

---

src/main/kotlin/io/snyk/plugin/net/ReportFalsePositiveRetrofitService.kt
src/main/kotlin/io/snyk/plugin/net/SnykApiClient.kt
src/main/kotlin/io/snyk/plugin/services/SnykApiService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotificationHelper.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanel.kt
src/test/kotlin/io/snyk/plugin/net/CliConfigServiceTest.kt
src/test/kotlin/io/snyk/plugin/net/SnykApiClientTest.kt
src/test/kotlin/io/snyk/plugin/net/TestNetUtils.kt
src/test/resources/test-fixtures/api-responses/snyk/sast_feedback-fail-404.json

Tests are omitted due to the fact that implemented functionality is related to UX and Net and is very hard(and very fragile on changes) to implement without numerous mocks -> all my attempts ending up testing mostly that mocks...
3 attempts to execute `feedback/sast` call was made:
```
2022-04-28 17:55:33,590 [  68842]  DEBUG - .snyk.plugin.net.SnykApiClient - Executing request to feedback/sast 
2022-04-28 17:55:34,291 [  69543]   WARN - .snyk.plugin.net.SnykApiClient - Failed to execute `feedback/sast` call: {"code":404,"message":"bad API request, please contact support@snyk.io for assistance","error":"unsupported url"} 
2022-04-28 17:55:34,291 [  69543]  DEBUG - .snyk.plugin.net.SnykApiClient - Executing request to feedback/sast 
2022-04-28 17:55:34,826 [  70078]   WARN - …
```

feat: `Report False Positive` API implementation [ROAD-543][ROAD-548]

---

.github/workflows/release.yml

add release notes to github release

fix: release notes

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/IssueDescriptionPanelBase.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykAuthPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/StatePanel.kt

fix: show container specific message on macOS [ROAD-910]

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/io/snyk/plugin/snykcode/core/PDU.kt

!!! Need first https://github.com/snyk/code-sdk-java/pull/38 to be merged and new java-code-sdk 2.3.2 released to maven !!!

fix: make re-try attempts for most api calls if not succeed for any reason (except 401 - auth failed) [ROAD-808] [ROAD-528]

---

.github/workflows/release.yml

chore: option to create major/minor releases via github button click [ROAD-672]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindow.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/resources/META-INF/plugin.xml

feat: expanding and collapsing of the issues [ROAD-575]

---

src/main/kotlin/io/snyk/plugin/snykcode/core/SCLogger.kt

Update Snyk Code text in task progress bar
Before
After

chore: [ROAD-1026] update snyk code progress bar text

---

src/main/kotlin/io/snyk/plugin/services/SnykCodeService.kt

fix typo from re-Analysing to re-analysing in progress bar

chore: fix typo from re-Analysing to re-analysing in progress bar [ROAD-1029]

---

.snyk
CHANGELOG.md
build.gradle.kts
src/integTest/kotlin/io/snyk/plugin/TestUtils.kt
src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/integTest/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/test/kotlin/io/snyk/plugin/services/download/SnykCliDownloaderServiceTest.kt

For some, automatic SNYK CLI downloads are unwanted. There is a new option now, to enable/disable those. Also, the location to where the CLI should be downloaded or can be found is now configurable.

feat: ✨ option to enable/disable automatic updates and to specify the CLI path

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt

_Updates the wording in settings menu for sending crash reports and analytics to Snyk._

chore: update wording for sending crash reports and analytics to Snyk

---

CONTRIBUTION.md

_Updates CONTRIBUTION.md with steps to run the extension._

docs: update CONTRIBUTION.md

---

.github/detekt/detekt-config.yml
CHANGELOG.md
build.gradle.kts
src/integTest/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykApiService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt

The checkboxes remained disabled, as we asked the API without a token.

fix: snyk code enablement from preference dialog during authentication

---

CHANGELOG.md
CONTRIBUTING.md
src/main/resources/META-INF/optional/withCsharp.xml
src/main/resources/META-INF/plugin.xml

Ensures we highlight issues in Rider.

fix: use Code annotator in C# [ROAD-1172]

---

gradle.properties

Introduces support of the latest IntelliJ version.

feat: support IntelliJ Platform 2022.3

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotifications.kt

Fixes contact url.
Ref: https://snyk.slack.com/archives/C04A02G7R96/p1670229146719409

fix: contact url

---

src/main/java/ai/deepcode/javaclient/core/DeepCodeUtilsBase.java
src/main/kotlin/snyk/iac/IacError.kt
src/main/kotlin/snyk/iac/IacResult.kt

Silence IaC false positive errors

fix: silence IaC warnings [HEAD-52]

---

CHANGELOG.md

Updated changelog with the recent IaC fixes

docs: modified changelog [HEAD-52]

---

CHANGELOG.md
src/main/kotlin/snyk/iac/IacError.kt
src/main/kotlin/snyk/iac/IacResult.kt

The error message is not relevant for the plugin and should be swallowed

fix: 🐛 ignore "invalid yaml file" error message from IaC

---

CHANGELOG.md
gradle.properties

Currently, the Jetbrains 2023.1 releases are not supported by the Snyk plugin. These changes enables them.

chore: update supported versions

---

CHANGELOG.md
gradle.properties
src/main/kotlin/snyk/common/CustomEndpoints.kt
src/test/kotlin/snyk/common/CustomEndpointsTest.kt

fix: remove api subdomain in snyk code URL when mt url is configured wrong

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt

fix: sanitize paths in navigational actions for snyk open source [SUP-894]

---

.github/detekt/detekt-baseline.xml
CHANGELOG.md
src/integTest/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/net/RetrofitClientFactory.kt
src/main/kotlin/io/snyk/plugin/services/SnykApiService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/common/CustomEndpoints.kt
src/test/kotlin/snyk/common/CustomEndpointsTest.kt

With this PR, given endpoints are validated against the pattern `https://app.xxxx.snyk.io/api`. Moreover, the correct API URLs are deducted, and exceptions in settings dialog are handled more gracefully.

fix: validate and normalize endpoints, handle exceptions better [HEAD-345]

---

src/main/kotlin/io/snyk/plugin/net/TokenInterceptor.kt
src/test/kotlin/io/snyk/plugin/net/TokenInterceptorTest.kt
src/test/kotlin/snyk/amplitude/api/AmplitudeExperimentApiClientTest.kt

feat: improve user agent

---

CHANGELOG.md
build.gradle.kts

Updates dependencies that had critical/high vulnerabilities in Snyk

fix: update dependencies [HEAD-249]

---

build.gradle.kts

fix: dependencies, don't exclude org.slf4j from iteratively [HEAD-880]

---

CHANGELOG.md
build.gradle.kts

fix high vulnerability in intellij plugin

fix: update JSON dependency [HEAD-915]

---

src/test/kotlin/io/snyk/plugin/analytics/ItlyHelperTest.kt
src/test/kotlin/snyk/amplitude/api/VariantTest.kt
src/test/kotlin/snyk/common/CustomEndpointsTest.kt

substitute hamcrest assertions with junit assertions

chore: cleanup some deprecations

---

CHANGELOG.md
gradle.properties

chore: enable 2023.3 [HEAD-1089]

---

.github/CODEOWNERS

chore: change codeowner to ide

---

CHANGELOG.md
EXTENSIONS.md
build.gradle.kts
src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
src/main/kotlin/io/snyk/plugin/extensions/SnykController.kt
src/main/kotlin/io/snyk/plugin/extensions/SnykControllerImpl.kt
src/main/kotlin/io/snyk/plugin/extensions/SnykControllerManager.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/io/snyk/plugin/extensions/SnykControllerImplTest.kt

Add an extension point to allow third-party plugins to interact with Snyk in the IDE.
Extension in a demo plugin (built with a local build of this branch)
[snyk-extension-point.webm](https://github.com/snyk/snyk-intellij-plugin/assets/23741/ccaf5a77-6dfc-47f1-af41-abb6cc5bf14e)

feat: snyk controller extension point

---

CHANGELOG.md

fix: updated changelog for disable analytics ticket

---

.github/workflows/build.yml

chore: update snyk job

---

build.gradle.kts

must be rebased on #477 after that has been merged.

fix: bump deps

---

CHANGELOG.md
gradle.properties
src/main/resources/META-INF/plugin.xml

https://snyksec.atlassian.net/browse/IDE-189
This PR shortens the name of the plugin to just "Snyk Security"
This change is based on multiple complaints from the field and customers.

[IDE-189] fix: shortened plugin's name to just Snyk Security

---

CHANGELOG.md
src/main/kotlin/snyk/common/lsp/Types.kt

Adds support for storing ignore details, even if not using them so far.

feat: add ignore details [IDE-172]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/settings/IssueViewOptionsPanel.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
src/main/kotlin/snyk/common/lsp/Types.kt
src/test/java/snyk/common/lsp/LanguageServerWrapperTest.kt
src/test/kotlin/io/snyk/plugin/extensions/SnykControllerImplTest.kt

IDE-173: This PR renders conditionally the Ignore settings in the UI

feat: render ignore settings [IDE-173]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeBulkFileListener.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/WelcomeNotifyActivity.kt
src/main/kotlin/snyk/code/annotator/SnykCodeAnnotatorLS.kt
src/main/kotlin/snyk/common/AnnotatorCommon.kt
src/main/kotlin/snyk/common/CustomEndpoints.kt
src/main/kotlin/snyk/common/lsp/LSCodeVisionProvider.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
src/main/kotlin/snyk/container/ContainerBulkFileListener.kt
src/main/kotlin/snyk/iac/IacBulkFileListener.kt
src/main/kotlin/snyk/iac/IgnoreButtonActionListener.kt
src/main/kotlin/snyk/trust/WorkspaceTrustService.kt
src/test/kotlin/io/snyk/plugin/net/CliConfigServiceTest.kt
src/test/kotlin/snyk/container/ContainerBulkFileListenerTest.kt
src/test/kotlin/snyk/errorHandler/SentryErrorReporterTest.kt

[IDE-205]
[IDE-205]: https://snyksec.atlassian.net/browse/IDE-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update code vision after scan, fix multi-project scan, fix parallel resource contention [IDE-204]

---

CHANGELOG.md

docs: remove 2.7.13 from changelog.md and add entries to 2.7.12

---

CHANGELOG.md
src/main/kotlin/snyk/common/lsp/LSCodeVisionProvider.kt

fix: add timeout to commands executed via code lenses

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/UIUtils.kt
src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
src/main/kotlin/io/snyk/plugin/ui/jcef/Utils.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/SuggestionDescriptionPanelFromLS.kt
src/test/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGeneratorTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSTest.kt

Adds an interaction to the Data Flow `<file name>:<line number>` to navigate to the file and line number. 
To test it, run `make build` in https://github.com/snyk/cli/pull/5153 and then update the path to the CLI in IntelliJ

feat: add data flow interaction [IDE-216]

---

src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt

At least one issue type should be selected. When being left with one, it wasn't possible to re-enable others.

fix: but in scan types enablement check

---

src/main/kotlin/snyk/common/CustomEndpoints.kt
src/test/java/snyk/common/lsp/LanguageServerWrapperTest.kt
src/test/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt
src/test/kotlin/snyk/common/CustomEndpointsTest.kt

Updates defaults & URL transformation to use https://api.xxx.snyk[gov].io/v1

feat: update default endpoint URL [IDE-128]

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/services/download/CliDownloader.kt
src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderTest.kt

The settings dialog now allows to select the CLI release channel

feat: allow selection of CLI release channel [IDE-270]

---

src/main/kotlin/io/snyk/plugin/ui/settings/IssueViewOptionsPanel.kt
src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt
src/main/kotlin/io/snyk/plugin/ui/settings/SeveritiesEnablementPanel.kt

chore: cleanup compiler warnings

---

src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt

feat: use link in settings dialog to describe release channels

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/JCEFDescriptionPanel.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSCodeTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSOSSTest.kt

In https://github.com/snyk/snyk-ls/pull/531 we're adding an `ideScript` injected variable that for now in IntelliJ we can just replace with nothing.
The only actual change in this is for `ideScript` but I installed `ktlint` and it formatted the file as well.

feat: intellij script for html [IDE-375] [IDE-367]

---

src/main/kotlin/io/snyk/plugin/analytics/AnalyticsScanListener.kt
src/main/kotlin/snyk/common/lsp/commands/ScanDoneEvent.kt
src/test/kotlin/io/snyk/plugin/analytics/AnalyticsScanListenerTest.kt

- Assign folder Path when sending analytics event

chore: send project path in analytics event [IDE-384]

---

CHANGELOG.md
gradle.properties
src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeBulkFileListener.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
src/main/kotlin/snyk/common/lsp/Types.kt

- enable 2024.2 in properties
- reduce time spent in UI thread by optimizing file listener

fix: make plugin compatible to 2024.2, reduce time in UI Thread [IDE-395]

---

.circleci/config.yml
.github/workflows/build.yml

Add quality gates and remove redundant scanning from workflow

chore: add quality gates

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/snyk/common/lsp/LanguageServerSettings.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt

Increases the required protocol version to 12, and also adds it to the LS initialization.

feat: update required protocol version to 12 [IDE-426] [IDE-376]

---

.github/workflows/readme-sync.yml

docs: add sync workflow

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/net/TokenInterceptor.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGenerator.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykPluginDisposable.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykTreeCellRenderer.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/leaf/SuggestionTreeNode.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/nodes/secondlevel/SnykFileTreeNode.kt
src/main/kotlin/snyk/code/annotator/CodeActionIntention.kt
src/main/kotlin/snyk/code/annotator/SnykAnnotator.kt
src/main/kotlin/snyk/code/annotator/SnykCodeAnnotator.kt
src/main/kotlin/snyk/code/annotator/SnykOSSAnnotatorLS.kt
src/main/kotlin/snyk/common/SnykCachedResults.kt
src/main/kotlin/snyk/common/lsp/LanguageServerSettings.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
src/test/kotlin/io/snyk/plugin/net/TokenInterceptorTest.kt
src/test/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGeneratorTest.kt
src/test/kotlin/snyk/common/lsp/SnykLanguageClientTest.kt

Cherry-picked some stability changes from the OAuth branch.

chore: freeze & shutdown improvements

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/events/SnykScanListenerLS.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
src/main/kotlin/snyk/common/SnykCachedResults.kt
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
src/main/kotlin/snyk/common/lsp/Types.kt
src/test/kotlin/io/snyk/plugin/services/download/CliDownloaderServiceIntegTest.kt
src/test/kotlin/snyk/common/lsp/SnykLanguageClientTest.kt

- Get issue list from Snyk Language Server Diagnostics instead of snyk.scan.
- Update ls protocol version to 14

feat: diagnostic issue model [IDE-543]

---

.github/workflows/release.yml

As we are going to align our stable releases with the CLI schedule, this is a first step to disable automated weekly release.

chore: modified Github action to release new stable versions manually

---

CHANGELOG.md
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
src/main/kotlin/snyk/container/ContainerService.kt
src/main/resources/META-INF/plugin.xml

fix: handle null values

---

src/main/kotlin/io/snyk/plugin/snykcode/SnykCodeBulkFileListener.kt

Fixes: Exception in refreshing of file annotations

fix: bulk file listener

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/snyk/code/annotator/SnykAnnotator.kt
src/main/kotlin/snyk/common/annotator/CodeActionIntention.kt
src/main/kotlin/snyk/common/annotator/ColorSettingsPage.kt
src/main/kotlin/snyk/common/annotator/ShowDetailsIntentionAction.kt
src/main/kotlin/snyk/common/annotator/SnykAnnotator.kt
src/main/kotlin/snyk/common/annotator/SnykCodeAnnotator.kt
src/main/kotlin/snyk/common/annotator/SnykOSSAnnotator.kt
src/main/kotlin/snyk/common/lsp/FolderConfigSettings.kt
src/main/kotlin/snyk/common/lsp/LanguageServerSettings.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/main/kotlin/snyk/common/lsp/Types.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/io/snyk/plugin/ui/jcef/OpenFileLoadHandlerGeneratorTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSCodeTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SuggestionDescriptionPanelFromLSOSSTest.kt
src/test/kotlin/snyk/common/lsp/LanguageServerWrapperTest.kt

- add color settings for snyk annotations
- send project specific oss scan configuration to language server on init & setting change
Color Settings:

feat: transmit project specific additional params [IDE-567]

---

src/main/kotlin/snyk/common/annotator/ColorSettingsPage.kt
src/main/kotlin/snyk/common/lsp/Types.kt

chore: rephrase color setting examples

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/Utils.kt
src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
src/main/kotlin/snyk/common/lsp/LanguageServerSettings.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt

- removed spaces between panels
- deactivated unnecessary field growth

fix: settings layout, glue delta setting to tree appearance

---

build.gradle.kts

chore: fixed parser of the Readme according to the latest state of the docs, to properly find the plugin description

chore: fixed parser of the Readme

---

src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
src/test/kotlin/io/snyk/plugin/extensions/SnykControllerImplTest.kt
src/test/kotlin/io/snyk/plugin/ui/BranchChooserComboBoxDialogTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt
src/test/kotlin/snyk/container/ContainerBulkFileListenerTest.kt

fix: show hand icon, refactor info node text construction

---

CHANGELOG.md
src/main/kotlin/snyk/common/lsp/LSDocumentationTargetProvider.kt
src/main/kotlin/snyk/common/lsp/LanguageServerSettings.kt
src/main/resources/META-INF/plugin.xml

Adds a documentation hover with the issue description & details (in case of Snyk Code).

feat: enable documentation hovers

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/SnykPostStartupActivity.kt
src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
src/main/kotlin/io/snyk/plugin/extensions/SnykControllerImpl.kt
src/main/kotlin/io/snyk/plugin/services/SnykTaskQueueService.kt
src/main/kotlin/io/snyk/plugin/services/download/CliDownloaderService.kt
src/main/kotlin/io/snyk/plugin/ui/SnykBalloonNotificationHelper.kt
src/main/kotlin/io/snyk/plugin/ui/actions/SnykRunScanAction.kt
src/main/kotlin/io/snyk/plugin/ui/settings/IssueViewOptionsPanel.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykPluginDisposable.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt
src/main/kotlin/snyk/trust/TrustedProjects.kt
src/test/kotlin/io/snyk/plugin/TestUtils.kt
src/test/kotlin/io/snyk/plugin/services/SnykTaskQueueServiceTest.kt
src/test/kotlin/io/snyk/plugin/ui/BranchChooserComboBoxDialogTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelIntegTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanelTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLSTest.kt
src/test/kotlin/io/snyk/plugin/ui/toolwindow/settings/ScanTypesPanelTest.kt
src/test/kotlin/snyk/container/ContainerBulkFileListenerTest.kt
src/test/kotlin/snyk/container/ContainerServiceIntegTest.kt

fix: shutdown exception logging, and auto-scan on startup

---

src/test/kotlin/snyk/container/ContainerBulkFileListenerTest.kt

fix: container test timeout

---

CHANGELOG.md
src/main/kotlin/snyk/common/EnvironmentHelper.kt
src/test/kotlin/io/snyk/plugin/cli/ConsoleCommandRunnerTest.kt

fix: respect no-proxy settings [IDE-663]

---

src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowSnykScanListenerLS.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt

Previously root nodes had a regression, that issue counts by severity were not shown. This PR fixes this.

fix: update root node presentation

---

src/main/kotlin/io/snyk/plugin/SnykFile.kt
src/main/kotlin/snyk/common/SnykCachedResults.kt

fix: check for disposal

---

src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt

fix: remove unnecessary exception from log

---

src/main/kotlin/snyk/common/lsp/settings/LanguageServerSettings.kt

chore: set hover verbosity to 0

---

CHANGELOG.md
src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt

Added a description of custom endpoints to settings dialog.
Before the change
After the change

feat: updating the custom endpoint description (IDE-735)

---

src/main/kotlin/io/snyk/plugin/ui/SnykSettingsDialog.kt

Update custom endpoint field in preference page if Snyk Language Server returns a new endpoint after authentication redirection.

fix: update custom endpoint in preference page [IDE-831]

---

.gitleaksignore
CHANGELOG.md
src/main/kotlin/io/snyk/plugin/SnykProjectManagerListener.kt
src/main/kotlin/io/snyk/plugin/services/SnykCliAuthenticationService.kt
src/main/kotlin/io/snyk/plugin/settings/SnykProjectSettingsConfigurable.kt
src/main/kotlin/io/snyk/plugin/ui/BranchChooserComboboxDialog.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt
src/test/kotlin/snyk/common/lsp/LanguageServerWrapperTest.kt

fix: only scan workspace folder, if folder is known to language server

---

src/main/kotlin/snyk/common/lsp/Types.kt

fix: folderConfig type [IDE-871]

---

src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt

fix error when closing project

fix: check for disposal before updating the issue cache

---

src/main/kotlin/io/snyk/plugin/Utils.kt

Small bugfix. If the project hadn't fully initialised, we would add all content roots under the first project. LS would end up with a complete list, but they'd be assigned to the wrong projects. This fixes that. 

fix: only include folders in their parent projects when calculating content roots [IDE-1012]

---

src/main/kotlin/snyk/common/lsp/SnykLanguageClient.kt

fix: use URI to determine file path

---

src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

fix: tree node race selection on windows

---

.github/workflows/resource-check.yml
src/main/kotlin/io/snyk/plugin/ui/jcef/ThemeBasedStylingGenerator.kt
src/main/resources/html/ScanSummaryInit.html
src/test/kotlin/io/snyk/plugin/ui/jcef/ThemeBasedStylingGeneratorTest.kt

Improves layout of delta scan summary panel.

fix: scale web fonts using 10px as a reference size. 

---

src/main/resources/html/ScanSummaryInit.html

The spinner is displayed while waiting for the LS to load.
- N/A - Couldn't see a linter for HTML/CSS
- N/A
- N/A

fix: Unsquish the loading spinner [IDE-1101]

---

.github/workflows/readme-sync.yml

Update the automation that pulls the JetBrains plugin page into the repository, from which the page populates the marketplace automatically. The title has changed from JetBrains plugins to JetBrains plugin. 
Fixes the failing jobs here
https://github.com/snyk/snyk-intellij-plugin/actions/workflows/readme-sync.yml

fix: fix the path to readme sync for github workkflow

---

src/main/kotlin/io/snyk/plugin/ui/settings/ScanTypesPanel.kt

fix: remove assignment of organization setting

---

src/main/kotlin/io/snyk/plugin/services/SnykApplicationSettingsStateService.kt
src/main/kotlin/io/snyk/plugin/ui/jcef/ApplyAiFixEditHandler.kt
src/main/kotlin/io/snyk/plugin/ui/jcef/GenerateAIFixHandler.kt
src/main/kotlin/io/snyk/plugin/ui/toolwindow/panels/PanelHTMLUtils.kt
src/main/kotlin/snyk/common/lsp/LanguageServerWrapper.kt

fix: only send issueId for AI fix

---

.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Contributor-Agreement.md

Updated CONTRIBUTING.md to clarify our expectations for changes and to ensure collaboration before work is done.
Added CODE_OF_CONDUCT.md and Contributor-Agreement.md. (Although the [`license/cla` check](https://cla-assistant.io/) will be enabled at a later date when we have time)
Updated the PR template to point to CONTRIBUTING.md and CODE_OF_CONDUCT.md.
- N/A
- N/A
- N/A
- N/A

docs: clarify pre-contribution asking [IDE-1240]

---

src/main/kotlin/snyk/common/lsp/hovers/LSDocumentationTargetProvider.kt

previously, sometimes a failed virtualfile retrieval caused a nullpointerexception. this pr fixes that. 

fix: npe in document hover
